### ISSUE TITLE
sqlparse.parse() returns inconsistent result on ORDER BY clause with column positions and DESC keyword

### ISSUE THREAD

**Issue by rockallite** [andialbrecht/sqlparse#101]
In version 0.1.7, for example:

    >>> # Normal for column names
    >>> sqlparse.parse('order by a, b desc')[0].tokens[4:]
    [<IdentifierList 'a, b d...' at 0x1019bbea8>]
    
    >>> # Normal for column names
    >>> sqlparse.parse('order by a desc, b')[0].tokens[4:]
    [<IdentifierList 'a desc...' at 0x1019bbc00>]
    
    >>> # Normal for pure column positions
    >>> sqlparse.parse('order by 1, 2')[0].tokens[4:]
    [<IdentifierList '1, 2' at 0x1019bbc88>]
    
    >>> # Ugly for column positions with DESC keyword
    >>> sqlparse.parse('order by 1, 2 desc')[0].tokens[4:]
    [<IdentifierList '1, 2' at 0x1019aad98>, <Whitespace ' ' at 0x1019bc940>,
     <Order 'desc' at 0x1019bc998>]
    
    >>> # Uglier if the first column position is followed by DESC keyword
    >>> sqlparse.parse('order by 1 desc, 2')[0].tokens[4:]
    [<Integer '1' at 0x1019bafc8>, <Whitespace ' ' at 0x1019bae10>,
     <Order 'desc' at 0x1019bacb0>, <Punctuation ',' at 0x1019bad08>,
     <Whitespace ' ' at 0x1019bad60>, <Integer '2' at 0x1019badb8>]

**Comment by ava-dylang** [comment]
Also suffering from this limitation, is this project dead?

**Comment by andialbrecht** [comment]
Nope, it isn't dead.

**Comment by piranna** [comment]
> Also suffering from this limitation, is this project dead?

But it needs a clean-up, pull-requests are welcome.

**Comment by ava-dylang** [comment]
I was looking into adding a test case, When to my surprise, it looks like the `sqlparser.lexer.tokenize` correctly identifies 'ORDER', 'BY' and 'DESC'.

    s = 'select * from foo order by column_name DESC;'
    stream = lexer.tokenize(s)
    tokens = list(stream)
    pprint.pprint(tokens)

```
[(Token.Keyword.DML, u'select'),
 (Token.Text.Whitespace, u' '),
 (Token.Wildcard, u'*'),
 (Token.Text.Whitespace, u' '),
 (Token.Keyword, u'from'),
 (Token.Text.Whitespace, u' '),
 (Token.Name, u'foo'),
 (Token.Text.Whitespace, u' '),
 (Token.Keyword, u'ORDER'),
 (Token.Text.Whitespace, u' '),
 (Token.Keyword, u'BY'),
 (Token.Text.Whitespace, u' '),
 (Token.Keyword, u'column_name'),
 (Token.Text.Whitespace, u' '),
 (Token.Keyword.Order, u'DESC'),
 (Token.Punctuation, u';')]
```

So its not the lexer :heavy_check_mark:

**Comment by andialbrecht** [comment]
@ava-dylang thanks for digging into this!

The actual problem was a bug in the grouping of identifier lists: "column_name DESC" and "1 DESC" were treated differently. IOW the bug only came up when the identifier was a number.

**Comment by ava-dylang** [comment]
@andialbrecht No thank you, I wasn't exactly sure where to start looking for the grouping mechanism; So thanks for taking this to the next step! Can I get this update on pypi or do I have to get this fix from source for a while?

**Comment by sourcedexter** [comment]
> I was looking into adding a test case, When to my surprise, it looks like the `sqlparser.lexer.tokenize` correctly identifies 'ORDER', 'BY' and 'DESC'.
> 
> ```
> s = 'select * from foo order by column_name DESC;'
> stream = lexer.tokenize(s)
> tokens = list(stream)
> pprint.pprint(tokens)
> ```
> 
> ```
> [(Token.Keyword.DML, u'select'),
>  (Token.Text.Whitespace, u' '),
>  (Token.Wildcard, u'*'),
>  (Token.Text.Whitespace, u' '),
>  (Token.Keyword, u'from'),
>  (Token.Text.Whitespace, u' '),
>  (Token.Name, u'foo'),
>  (Token.Text.Whitespace, u' '),
>  (Token.Keyword, u'ORDER'),
>  (Token.Text.Whitespace, u' '),
>  (Token.Keyword, u'BY'),
>  (Token.Text.Whitespace, u' '),
>  (Token.Keyword, u'column_name'),
>  (Token.Text.Whitespace, u' '),
>  (Token.Keyword.Order, u'DESC'),
>  (Token.Punctuation, u';')]
> ```
> 
> So its not the lexer ✔️

The only reason this worked is that "column_name" was used and it was detected as a keyword. 
just replace "column_name" with anything else and it will fail every single time.
