### ISSUE TITLE
Very Very ( > 5s ) Parsing Big Queries

### ISSUE THREAD

**Issue by nikilster** [andialbrecht/sqlparse#135]
Hey!  I've been trying figure out why my django query was running slow and after profiling it - it seems to spend most of the time in two to three sqlparse calls - sql.py:254(token_next_by_instance), grouping.py:150(group_identifier), and grouping.py:174(_next_token).  I basically have 2-3 queries that have an IN clause with ~300 - ~1200 (the biggest one) ids in each.  Is there a way to make this faster?

https://www.dropbox.com/s/yctmvdp1ypwiug6/Screenshot%202014-04-10%2023.19.19.png

**Comment by andialbrecht** [comment]
This should be fixed in 2bde1b9e494bc8673e0967a7b1f59150131659cc.

**Comment by minexew** [comment]
Parsing is still awfully slow for big files.

For example, this SQL which inserts about 65k lines in a single statement didn't finish parsing in 5 minutes:
https://github.com/mangoszero/database/blob/release20/World/Setup/FullDB/creature.sql
(Python 3.4, Win32, Intel Xeon v3-1241, more than enough RAM)

```tlist.tokens.remove()``` as mentioned in #62 seems to significantly contribute to the slowness.

**Comment by vmuriart** [comment]
@minexew @nikilster If you guys get a chance, let me know if you guys are able to test with the latest master branch. 
On my poor old laptop, @minexew's example initially took ~90 minutes to complete on `0.1.19`.

Currently I am getting the following results: 
`5m 51s`, `6m 23`
(sqlparse `master` branch, Python 2.7, Win8.1, i5, 8gb memory)

`3m 38s`, `3m 52s`
(sqlparse `development` branch, Python 2.7, Win8.1, i5, 8gb memory)

In all tests I ran them as `sqlparse.parse(sql)`.
