### ISSUE TITLE
Add option for comma-first notation

### ISSUE THREAD

**Issue by hallpower** [andialbrecht/sqlparse#141]
I use this library on an almost daily basis (from within Sublime Text). I would love to have the ability to switch to comma first notation for column names:

select foo1
          , foo2
          , foo3
from bar

instead of

select foo1, 
          foo2,
          foo3
from bar

If you're not interested in implementing this feature, would you mind pointing me in the direction of where I might change it myself?

Many thanks for your hard work!

**Comment by edbrannin** [comment]
Not sure if the code-review comment generated a notification, so:

It would be nice if the comma were back 2 spaces from this implementation, so list-items would line up

**Comment by andialbrecht** [comment]
You're right! The suggested formatting looks nicer. I'll have a look at it.

Ed Brannin <notifications@github.com> schrieb am Fr., 16. Sep. 2016 23:43:

**Comment by andialbrecht** [comment]
Done.

**Comment by edbrannin** [comment]
Thank you!
