### ISSUE TITLE
feature request- option to disable reindent of 'IN()' params

### ISSUE THREAD

**Issue by jvanasco** [andialbrecht/sqlparse#147]
the current behavior will reindent 'IN' elements to one per-line:

	WHERE id IN (%(id_1)s,
					   %(id_2)s,
					   %(id_3)s,
					   %(id_4)s,
					   %(id_5)s,
					   %(id_6)s,
					   %(id_7)s,
					   %(id_8)s,
					   %(id_9)s,
					   %(id_10)s)

When dealing with large IN queries (like pulling out 100 items by id), this makes the code harder to read.  

it would be great to be able to disable this behavior, or set some sort of threshold.

**Comment by andialbrecht** [comment]
Sorry, this slipped through... The feature is already implemented in 0.2.0. Just use the `wrap_after` configuration/command line option.

Related commit is 9b84aac37a4099f4788508f98b7b1ed3010c424e
