### ISSUE TITLE
IF/WHILE/CASE etc. blocks improperly parsed

### ISSUE THREAD

**Issue by anjoola** [andialbrecht/sqlparse#161]
If you try to run `parse` on the following SQL statement:

    CREATE FUNCTION test() RETURNS BOOLEAN
        BEGIN
            IF (TRUE) THEN RETURN TRUE; END IF;
        END ;

    SELECT * FROM table;

Result: `(<Statement 'CREATE...' at 0x1f03cc8>)`

Only a single `CREATE` statement is parsed. This is because the END IF keyword is treated as an END which closes the IF block, and a new IF which is unclosed.

However, running `parse` on this works, but isn't valid, at least for MySQL (http://dev.mysql.com/doc/refman/5.7/en/if.html). 

    CREATE FUNCTION test() RETURNS BOOLEAN
        BEGIN
            IF (TRUE) THEN RETURN TRUE; END;
        END ;

    SELECT * FROM table;

Result: `(<Statement 'CREATE...' at 0x1f03cc8>, <Statement 'SELECT...' at 0x1f03b48>)`

**Comment by swillits** [comment]
Works in the latest version.

**Comment by andialbrecht** [comment]
Thanks for the feedback!
