### ISSUE TITLE
Formatting of case statement; from tables list in sub-query

### ISSUE THREAD

**Issue by Freewilly3d** [andialbrecht/sqlparse#163]
**BEFORE - CASE (formats correctly if case statement hightlighted alone; the sample is a case in a sub query)**
         
      case  when T432521.X_ANALYSIS_TYPE = 'ACT' and T432521.X_RESOURCE_TYPE = 'CRECU' and T439691.LEVEL04_CODE = '2ND_GEN_PROP_IMPROV' then 'Property Improvements' when T432521.X_ANALYSIS_TYPE = 'ACT' and T439691.LEVEL05_CODE = '2ND_GEN_TENANT_IMPRV' and T432521.X_RESOURCE_TYPE in ('TIMAK', 'TISTD') then 'Tenant Improvements' when T432521.X_ANALYSIS_TYPE = 'ACT' and T432521.X_RESOURCE_TYPE = 'COMM' and T439691.LEVEL05_CODE = '2ND_GEN_LEASE_COMM' then 'Leasing Commisions' else 'N/A' end  as c2,

**AFTER**

END) AS c1, CASE WHEN T432521.X_ANALYSIS_TYPE = 'ACT'
      AND T432521.X_RESOURCE_TYPE = 'CRECU'
      AND T439691.LEVEL04_CODE = '2ND_GEN_PROP_IMPROV' THEN 'Property Improvements' WHEN T432521.X_ANALYSIS_TYPE = 'ACT'
      AND T439691.LEVEL05_CODE = '2ND_GEN_TENANT_IMPRV'

**BEFORE - from table list in sub-querie**

               T371585.DIVISION_SORT_ORDER_CD as c6
          from 
               WC_GEOGRAPHIC_MARKET_D T371585 /* Dim_WC_GEOGRAPHIC_MARKET_D */ ,
               WC_PROPERTY_D T371579 /* Dim_WC_PROPERTY_D */ ,
               W_PROJ_COST_LINE_F T432521 /* Fact W_PROJ_COST_LINE_F */ ,
               WC_PHASE_CODE_HIER_D T439691 /* Dim_WC_PHASE_CODE_HIER_D */ ,

**AFTER (extra cr and tabs after , following /*comment */  then cr and tabs before table name - each table indented more  dashes represent additional spacing added**

               T371585.DIVISION_SORT_ORDER_CD as c6

FROM WC_GEOGRAPHIC_MARKET_D T371585 /* Dim_WC_GEOGRAPHIC_MARKET_D */
---------------------------,
----------------------------WC_PROPERTY_D T371579 /* Dim_WC_PROPERTY_D */
----------------------------------------------,
-----------------------------------------------W_PROJ_COST_LINE_F T432521 /* Fact W_PROJ_COST_LINE_F */
                                                                                     ,

**Comment by andialbrecht** [comment]
Thanks for the example. Sometimes it's interesting how such obvious use cases slip through :)

What I've encountered so far:

formatting from statements works pretty well

```python
>>> print(sqlparse.format("from foo as bar, \n foo2 as foobar \n", reindent=True))

from foo as bar,
     foo2 as foobar
```

adding single line comments has issues:

```python
>>> print(sqlparse.format("from foo as bar, -- comment 1 \n foo2 as foobar \n", reindent=True))

from foo as bar,
     -- comment 1

     foo2 as foobar
```

(not bad, but not perfect: there's an extra line break which could be removed), but there's a different behavior when using multi-line comments:

```python
>>> print(sqlparse.format("from foo as bar, /* comment 1 */\n foo2 as foobar /* comment 2*/ \n", reindent=True))

from foo as bar,
     /* comment 1 */
     foo2 as foobar /* comment 2*/
```

But with the comma after the comment it just fails:

```python
>>> print(sqlparse.format("from foo as bar /* comment 1 */, \nfoobar" , reindent=True))

from foo as bar /* comment 1 */
                ,
                foobar
```

**Comment by andialbrecht** [comment]
ahh... it's not closed yet... there's still an issue with the example statement given here.

**Comment by andialbrecht** [comment]
Formatting is now fine for the given examples, at least when I extend them to more or less complete queries:

```python
>>> sql = """select T371585.DIVISION_SORT_ORDER_CD as c6
      from 
           WC_GEOGRAPHIC_MARKET_D T371585 /* Dim_WC_GEOGRAPHIC_MARKET_D */ ,
           WC_PROPERTY_D T371579 /* Dim_WC_PROPERTY_D */ ,
           W_PROJ_COST_LINE_F T432521 /* Fact W_PROJ_COST_LINE_F */ ,
           WC_PHASE_CODE_HIER_D T439691 /* Dim_WC_PHASE_CODE_HIER_D */"""
>>> print(sqlparse.format(sql, reindent=True))
select T371585.DIVISION_SORT_ORDER_CD as c6
from WC_GEOGRAPHIC_MARKET_D T371585 /* Dim_WC_GEOGRAPHIC_MARKET_D */ ,
     WC_PROPERTY_D T371579 /* Dim_WC_PROPERTY_D */ ,
     W_PROJ_COST_LINE_F T432521 /* Fact W_PROJ_COST_LINE_F */ ,
     WC_PHASE_CODE_HIER_D T439691 /* Dim_WC_PHASE_CODE_HIER_D */
```
