### ISSUE TITLE
Wheel packaging format for pypi.org

### ISSUE THREAD

**Issue by stonebig** [andialbrecht/sqlparse#165]
Would it be possible to get sqlparse on a wheel package format, on pypi ?

**Comment by stonebig** [comment]
maybe you have first to drop 2to3 , so it may not be a 5 minutes request

**Comment by andialbrecht** [comment]
The 0.2.0 branch doesn't need 2to3 already.

**Comment by stonebig** [comment]
Excellent ! I didn't notice it 

Do you consider 0.2.0 branch stable enough ? (no more bug than 0.1.14)

**Comment by andialbrecht** [comment]
0.2.0 is stable as it is right now. But I'd like to introduce some often requested features that could cause backwards incompatible changes. Hence it's labelled "experimental" (but in fact "stable" as it's is).

**Comment by stonebig** [comment]
Super.
Thanks a lot for this nice package.  I'll put a version  0.1.99 when doing a wheel with your 0.2.0 of today, to clearly distinguish it's not 0.1.14

**Comment by edmorley** [comment]
I was about to file an issue for this; any luck here? :-)

**Comment by andialbrecht** [comment]
yepp, the next release (0.2.0) will have wheels.

**Comment by edmorley** [comment]
Many thanks! :-)

**Comment by kevin-brown** [comment]
> yepp, the next release (0.2.0) will have wheels.

I hate to dig this ticket up again, but 0.2.0 and 0.2.1 only have the source versions available. It looks like the configuration for universal wheels is in place, so my guess is that either they just weren't generated (`bdist_wheel`) or were not uploaded.

**Comment by andialbrecht** [comment]
My fault! wheels for 0.2.0 and 0.2.1 are available on PyPI now.
