### ISSUE TITLE
sqlparse requires instantiation to call static methods

### ISSUE THREAD

**Issue by coyotlinden** [andialbrecht/sqlparse#173]
In a Django views.py I have:

import sqlparse

    :

statement = sqlparse.parse(query_string)

and this throws:

Traceback:
File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py" in get_response
  100.                     response = callback(request, *callback_args, **callback_kwargs)
File "<something>/views.py" in display_name_search
  684.         filter = request.GET.getlist('filter')
File "<something>/common/util.py" in wrapper
  210.             result_set = func(*__args, **__kw)
File "<something>/agent/views.py" in _agent_id_search

Exception Type: TypeError at /agent/search/xxxxxxxx/
Exception Value: 'module' object is not callable

unless I use:

sqlparse = sqlparse()

before the call.  None of the documentation suggests this is needed.

**Comment by coyotlinden** [comment]
Update: 

After a few more tests, this changed to:

xception Type: UnboundLocalError at /agent/search/xxxxx/
Exception Value: local variable 'sqlparse' referenced before assignment

**Comment by andialbrecht** [comment]
In fact, that isn't needed. It looks a lot like a bug in your views.py. Maybe due to a wrongly declared import or maybe you're overriding the imported name with a variable or function name somewhere.

The correct usage is:

{{{
import sqlparse
statement = sqlparse.parse(query_string)
}}}

**Comment by coyotlinden** [comment]
Apparently restarting apache fixed this.
