### ISSUE TITLE
Problem with field name that contains keyword as `update`

### ISSUE THREAD

**Issue by MiCHiLU** [andialbrecht/sqlparse#175]
example:

`select _update from _table`

I got broken SQL as below:

```
SELECT _
UPDATE
FROM _TABLE
```

**Comment by andialbrecht** [comment]
Thanks for pointing this out! This is a bug in the parser that doesn't allow identifiers to start with an underscore. But according to the PostgreSQL docs (for example) this is totally valid: "SQL identifiers and key words must begin with a letter (a-z, but also letters with diacritical marks and non-Latin letters) or an underscore (_)." ([PostgreSQL 8.2 docs](http://www.postgresql.org/docs/8.2/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS))

I'm already working on a fix for this.

**Comment by MiCHiLU** [comment]
Thanks for your work!
