### ISSUE TITLE
Incorrect identification of array literals as Identifier

### ISSUE THREAD

**Issue by runfalk** [andialbrecht/sqlparse#176]
When trying to parse "ARRAY[%s, %s]" I get something like this:

```python
>>> pprint(list(sqlparse.parse("ARRAY[%s, %s]")[0].flatten()))
[<Builtin 'ARRAY' at 0x7f6b7c61b208>, <Name '[%s, %...' at 0x7f6b7c61b260>]
```

I expect somthing similar to this:

```python
>>> pprint(list(sqlparse.parse("ARRAY[%s, %s]")[0].flatten()))
[<Builtin 'ARRAY' at 0x7f6b7c61b208>,
 <Punctuation '[' at 0x7f6b7c612f18>,
 <Placeholder '%s' at 0x7f6b7c612f70>,
 <Punctuation ',' at 0x7f6b7c612fc8>,
 <Whitespace ' ' at 0x7f6b7c61b050>,
 <Placeholder '%s' at 0x7f6b7c61b0a8>,
 <Punctuation ']' at 0x7f6b7c61b100>]
```

Is this intended behavior?

**Comment by darikg** [comment]
I think you're on an older version of sqlparse? In master it does this, not that it's any better:

```
In[6]: list(parse('ARRAY[%s, %s]')[0].flatten())
Out[6]: [<Builtin 'ARRAY' at 0x42b1638>, <ArrayIndex '[%s, %...' at 0x42b1958>]
```

This is related to a PR I made, #170, which was a quick fix to parse square bracket contents as an array index. It was kinda kludgey though, and the entire contents of the square brackets get parsed into a single token, so flatten() won't do what you want it to. I agree it should though. I need to treat square brackets as a grouping operator just like parens. The tricky part is handling mixed parens and brackets, like `some_array[(1 + 2) * another_array[(etc)]]`. I'll give it another shot when I get a chance this week.

**Comment by andialbrecht** [comment]
@darikg, that'd be great. I've missed this in your PR. You're right "[%s, %s]" shouldn't be parsed as a single token :)

**Comment by runfalk** [comment]
@darikg: I am using 0.1.14 (the latest version on PyPI).

**Comment by andialbrecht** [comment]
Yes, the change @darikg is talking about, isn't released yet.

Andreas Runfalk <notifications@github.com> schrieb am Mi., 4. März 2015 um
11:06 Uhr:
