### ISSUE TITLE
Should get_alias() return an alias or None for identifiers like `schema.table`?

### ISSUE THREAD

**Issue by darikg** [andialbrecht/sqlparse#185]
Because of #171, there was an unexpected change in behavior of get_alias() for qualified tables like `foo.bar`

Old behavior (v0.1.14): get_alias() on `foo.bar` returns `None`
New behavior (v0.1.15): get_alias() on `foo.bar` returns `bar`

I'm not sure what the correct behavior ought to be. On one hand, the original behavior makes sense because no explicit alias was added. On the other hand, the new behavior makes sense too because in the rest of the sql query `bar` does in fact act as an alias for the identifier `foo.bar`

**Comment by andialbrecht** [comment]
That's a bug. To get "bar" you should use the `get_name()` method. `get_alias()` should only return a value other than `None` when an alias is explicitly defined.

**Comment by darikg** [comment]
Thanks!
