### ISSUE TITLE
Can't determine statement type when it begins with -- comment

### ISSUE THREAD

**Issue by mehaase** [andialbrecht/sqlparse#186]
Similar to #144, but a bit more specific. The following query parses correctly but subsequent calls to `get_type()` return `UNKNOWN` instead of `INSERT`:

```sql
-- Comment 2
INSERT INTO `foo` VALUES ('bar','baz','bat');
```

Here's what happens:

```python
>>> import sqlparse
>>> s = sqlparse.parse('''-- Comment 2
... INSERT INTO `foo` VALUES ('bar','baz','bat');
... ''')
>>> print(s[0])
-- Comment 2
INSERT INTO `foo` VALUES ('bar','baz','bat');
>>> s[0].get_type()
'UNKNOWN'
```

I'm running into this problem when trying to parse a MySQL dump file that has a comment followed by a series of insert statements. I'm using `parsestream()` to break the MySQL file into discrete statements, and it groups the lines as indicated above.

**Comment by mehaase** [comment]
Sorry for all of the e

**Comment by andialbrecht** [comment]
Comments are now ignored when calling get_type(). Thanks for reporting!
