### ISSUE TITLE
Add equality comparsion for statements

### ISSUE THREAD

**Issue by thedrow** [andialbrecht/sqlparse#189]
I wanted to use sqlparse to check if the ORM I'm using is generating the correct SQL statements in a test but sqlparse doesn't support comparing statements.

**Comment by andialbrecht** [comment]
What would you expect from such a comparision? It would be easy to implement to check if two statements are lexically equal, maybe it'd be easy to ignore whitespaces at this point too. But any comparision that would go deeper will be very tricky to implement.

**Comment by thedrow** [comment]
I need to know if two queries are the same but the order doesn't matter.
So if I have:
```sql
SELECT * FROM foo WHERE bar = 1 AND baz = 2
```
and
```sql
SELECT * FROM foo WHERE baz = 2 AND bar = 1
```

I'd consider them equal.

**Comment by andialbrecht** [comment]
I expect many more cases here where two different statements should be considered equal. At the end of the day providing this feature would require a solid statement analyzer. IMO a query analyzer is beyond the scope of this project.
