### ISSUE TITLE
support "source filename.sql"  or ". filename"

### ISSUE THREAD

**Issue by jukebox** [andialbrecht/sqlparse#190]

**Comment by andialbrecht** [comment]
Could you add a description with a bit more details please.

**Comment by piranna** [comment]
I think he means something like the include statement I invented some years
ago ;-)

**Comment by jukebox** [comment]
>>> import sqlparse
>>> parse = sqlparse.parse("source test.sql")
>>> for s in parse:
...     print(s.get_type())
... 
UNKNOWN

**Comment by jukebox** [comment]
do you need more feedback ?

**Comment by phdru** [comment]
sqlparse should do
```python
parse = sqlparse.parsestream(open("test.sql"))
```
but it currently doesn't — lexer.py only allows strings and StringIO. It should also allow files.
