### ISSUE TITLE
New lexer.py removing temp table declarations mssql

### ISSUE THREAD

**Issue by Deric4** [andialbrecht/sqlparse#192]
The comment stripper is removing temp table declarations in mssql
```
CREATE TABLE #MY_TEMP_TABLE
(
    MY_STRING_1 VARCHAR(8),
     MY_STRING_2 VARCHAR(8)
);

SELECT * FROM #MY_TEMP_TABLE
```
....turns into

```
CREATE TABLE
(
     MY_STRING_1 VARCHAR(8),
     MY_STRING_2 VARCHAR(8)
);

SELECT * FROM
```

We are noticing this in the 0.1.15 release but using 0.1.13 without issue.

Upon further inspection it looks like line 170 in lexer.py is the new addition that's causing the problem.
```
(r'(--|#).*?$', tokens.Comment.Single)
```

Reverting to `(r'--.*?$', tokens.Comment.Single),` has everything working as before.

**Comment by andialbrecht** [comment]
Thanks for reporting and pointing me to the right line that causes this issue!
