### ISSUE TITLE
Query splitting failure case

### ISSUE THREAD

**Issue by swillits** [andialbrecht/sqlparse#193]
The example below demonstrates a case where query splitting fails to recognize there are two queries, and instead returns just one. If the DECLARE line is removed, then splitting returns two queries.

I'm expecting everything from CREATE to END to be the first query, and the SELECT to be the second query.

I have other cases where it fails as well. 

Python 2.7.6

```
import sqlparse

sql = """CREATE FUNCTION a(x VARCHAR(20)) RETURNS VARCHAR(20)
BEGIN
 DECLARE y VARCHAR(20);
 RETURN x;
END;
SELECT * FROM a.b;
"""

queries = sqlparse.split(sql)
print "%d queries" % (len(queries))
print "-----------------------------------------"
for query in queries:
	print query
	print "-----------------------------------------\n\n\n"


# 1 queries
# -----------------------------------------
# CREATE FUNCTION a(x VARCHAR(20)) RETURNS VARCHAR(20)
# BEGIN
#  DECLARE y VARCHAR(20);
#  RETURN x;
# END;
# SELECT * FROM a.b;
# -----------------------------------------
```

**Comment by andialbrecht** [comment]
Thanks for reporting! The splitter expected DECLARE only outside the BEGIN...END block.
