### ISSUE TITLE
Query splitting failure case #2

### ISSUE THREAD

**Issue by swillits** [andialbrecht/sqlparse#194]
Similar to the issue #193, but now with an added IF statement which is causing a problem.

```
import sqlparse

sql = """CREATE FUNCTION a(x VARCHAR(20)) RETURNS VARCHAR(20)
BEGIN
 DECLARE y VARCHAR(20);
 IF (1 = 1) THEN
 SET x = y;
 END IF;
 RETURN x;
END;
SELECT * FROM a.b;
"""

**Comment by andialbrecht** [comment]
Thanks for reporting! You're right. This was very similar to #193. Expect another bug fix release soon.
