### ISSUE TITLE
sublime3 issue 

### ISSUE THREAD

**Issue by salahaldin** [andialbrecht/sqlparse#209]
Hello,

I am runnig the example from sublime console 
   >>> sql = 'select * from someschema.mytable where id = 1'
   >>> res = sqlparse.parse(sql)
However I get this error
AssertionError: token type must be simple type or callable, not Token.Comment.Multiline
any ideas will be appreciated 

Regards

**Comment by andialbrecht** [comment]
I'm not able to reproduce this on a regular Python shell. Which version of sqlparse are you using? `sqlparse.__version__` should show it in your console.

**Comment by salahaldin** [comment]
Hello I am using the last version from github, Also, I am using sublime 3 on windows environment

**Comment by ava-dylang** [comment]
the python interpreter embeded in sublime is isolated from any other interpreter, I was unable to install any modules onto its runtime whne I was interested in doing so.

**Comment by vmuriart** [comment]
@salahaldin I think you are using one of the forks that were made into the subl3 plugin. Did you verify its not [zsong's SqlBeutifier](https://github.com/zsong/SqlBeautifier) ?

@ava-dylang you can attach modules subl3 to use them as plugin's. See the above fork.

**Comment by ava-dylang** [comment]
@vmuriart just put the module in the extension? That is quite simple, last I tried I was trying to use a git2 for py, which is compiled and am not exactly sure what constraints that adds. But thats off topic here.

**Comment by vmuriart** [comment]
As an aside... 

@ava-dylang Its pretty simple. You need to do some mapping from the module to sublime. 
Take a look at this [guide](https://github.com/Enteleform/Presentations) to get you started.

**Comment by vmuriart** [comment]
@andialbrecht this issue can probably be closed since it's referring to an issue in a different project uses a modified version of `sqlparse`.

**Comment by andialbrecht** [comment]
Yeah, please file an issue at https://github.com/zsong/SqlBeautifier if you have any problems getting the formatter running in Sublime.
