### ISSUE TITLE
Can not support utf-8 sql parse

### ISSUE THREAD

**Issue by winlin** [andialbrecht/sqlparse#212]
The SQL is:
insert into tblobject( description, guid, subclass, instanceclass, instanceclassloc, issueby, issueby_oid, issueby_class, issueto, issueto_oid, issueto_class, issuetime, lastmodifytime, idalternative, scrapped, archived, stop)values('WiFi','918df0d3ccb34d54a78b2c2392330c8b','tbltag','tbltaggpsloc','位置信息','48351176b3294feda1b22b13adde2535', (select oid from tblobject where guid = '48351176b3294feda1b22b13adde2535'),(select instanceclass from tblobject where guid = '48351176b3294feda1b22b13adde2535'),'48351176b3294feda1b22b13adde2535', (select oid from tblobject where guid = '48351176b3294feda1b22b13adde2535'),(select instanceclass from tblobject where guid = '48351176b3294feda1b22b13adde2535'),'2015-12-01 10:11:10','2015-12-01 10:11:10','',0,0,0)

My Code is:
parsed = sqlparse.parse(sql, encoding='utf-8')
stmt = parsed[0]
for i in stmt.tokens:
     print i

there will an exception:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 68-71: ordinal not in range(128)

**Comment by andialbrecht** [comment]
A fix for this issue will be pushed soon, but it may take a while before I'm able the release the next version. Inbetween you can typecast a token before printing it:
```python
for i in stmt.tokens:
    print unicode(i)
```
Thanks for reporting!

**Comment by winlin** [comment]
That's great. Thanks a lot.
