### ISSUE TITLE
Format() function can not strip the first whitespace of the statement.

### ISSUE THREAD

**Issue by shenlongxing** [andialbrecht/sqlparse#213]
I use format(stmt, strip_whitespace=True) to strip the whitespaces of the statement. And i find the whitespace can not be stripped when it is the first character of the statement.

Here is a example:
[root@gorilla sqlparse-master]# python
Python 2.6.6 (r266:84292, Nov 22 2013, 12:16:22) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> import sqlparse
\>\>\> sql='    select 1'
\>\>\> sqlparse.format(sql, strip_whitespace=True)
u' select 1'
\>\>\> 

I think it is a bug. If you agree with that i will send you a patch.
Thank you!

**Comment by andialbrecht** [comment]
Yes, that's a bug. A patch would be nice!

Shen Longxing <notifications@github.com> schrieb am Mo., 14. Dez. 2015
09:13:

**Comment by andialbrecht** [comment]
Fixed in ac3fdfd2714b275e6def5ec2cf8bf92cabe56b60
