### ISSUE TITLE
sqlparse does not support while loop for MySQL.

### ISSUE THREAD

**Issue by shenlongxing** [andialbrecht/sqlparse#215]
I use sqlparse to parse SQL statements of MySQL, and it fails when there are while loops.

Here is the example:
\>\>\> import sqlparse
\>\>\> 
\>\>\> sql='''
... create procedure genUsers()
... begin
...   declare i int default 0;
...   while i < 40 do
...     insert into users(userID,userName,password) values(i,concat('username',i),concat('password',i));
...     set i = i + 1;
...   end while;
... end　
... '''
\>\>\> 
\>\>\> 
\>\>\> 
\>\>\> queries = sqlparse.split(sql)
\>\>\> print "%d queries" % (len(queries))
2 queries
\>\>\> print "-----------------------------------------"
\-----------------------------------------
\>\>\> for query in queries:
\.\.\.\     print query
\.\.\. \    print "-----------------------------------------\n\n"
\.\.\. 
create procedure genUsers()
begin
  declare i int default 0;
  while i < 40 do
    insert into users(userID,userName,password) values(i,concat('username',i),concat('password',i));
    set i = i + 1;
end while;
-----------------------------------------

end
-----------------------------------------

\>\>\>

**Comment by andialbrecht** [comment]
Pull request merged in a72f04cd1a3030dd1ac0a34b8fb6dba1b808fe97
