### ISSUE TITLE
Inconsistent behavior of self.parent (and has_ancestor())

### ISSUE THREAD

**Issue by bc-lee** [andialbrecht/sqlparse#226]
(python 3.4, sqlparse 0.1.18)
The sample code is follows:

```python
import sqlparse
sql = "CREATE TABLE test();"
result = sqlparse.parse(sql)
for item in result[0].tokens:
    print("Type: %s, ttype: %s, Parent: %s, has_ancestor: %s" % \
        (type(item), item.ttype, item.parent, item.has_ancestor(result[0])))
```

I've expected that all of results have `has_ancestor: True`, but only one has such result.

```python
Type: <class 'sqlparse.sql.Token'>, ttype: Token.Keyword.DDL, Parent: None, has_ancestor: False
Type: <class 'sqlparse.sql.Token'>, ttype: Token.Text.Whitespace, Parent: None, has_ancestor: False
Type: <class 'sqlparse.sql.Token'>, ttype: Token.Keyword, Parent: None, has_ancestor: False
Type: <class 'sqlparse.sql.Token'>, ttype: Token.Text.Whitespace, Parent: None, has_ancestor: False
Type: <class 'sqlparse.sql.Function'>, ttype: None, Parent: CREATE TABLE test();, has_ancestor: True
Type: <class 'sqlparse.sql.Token'>, ttype: Token.Punctuation, Parent: None, has_ancestor: False
```

Due to such behavior, it is not easy to traverse items in the parsed statement.

**Comment by ava-dylang** [comment]
indeed, this is very annoying

**Comment by vmuriart** [comment]
in which cases should it return `False`?

**Comment by thorsummoner** [comment]
When I started to work with sqlparse it felt like working in an xml node tree object thing; so that's where my assumption of: where in going into a child node should have the express ability to traverse back to the parent node; came from, traversing up parents should only fail IMO, where this is literally no parent node to go to. In Sqlparse that highest node is the whole sql string, that is to say the parent of a single query is the object container for a string that [possibly] contains multiple sql queries.

**Comment by vmuriart** [comment]
I think I see what you guys mean. There are multiple sections of code that for `token grouping` to form the different `TokenLists` but on [some of them](https://github.com/andialbrecht/sqlparse/blob/master/sqlparse/engine/grouping.py#L36) the parent is never set.

**Comment by andialbrecht** [comment]
Thanks for pointing at this! The group_tokens() method should be called,
which sets parent on the nodes (
https://github.com/andialbrecht/sqlparse/blob/master/sqlparse/sql.py#L365)

Vik <notifications@github.com> schrieb am Di., 3. Mai 2016 um 03:28 Uhr:

**Comment by vmuriart** [comment]
@andialbrecht I been playing around with the source to refactor some of it out and keep the parse logic. You can take a look at [my fork](https://github.com/vmuriart/sqlparse) but the section in question has been refactored [here](https://github.com/vmuriart/sqlparse/blob/master/sqlparse/grouping.py#L76).

**Comment by andialbrecht** [comment]
ok, I see your refactoring already uses group_tokens() as it should be.

**Comment by vmuriart** [comment]
Yea, though i wouldn't `pr` my fork since it breaks alot of other features.

**Comment by vmuriart** [comment]
The function [`parent_name`](https://github.com/andialbrecht/sqlparse/blob/master/sqlparse/sql.py#L414) probably doesn't help the situation either. The function is referring to the prefix of `TokenList` rather than the grouping parent.

**Comment by thorsummoner** [comment]
Is there room in the api to support node hierarchy navigation in addition to the existing Tokenizer data? the xml api uses a `getparent` method, I would generally prefer properties than methods for simple getters, but another part of me wants to model the hierarchy navigation off other well established hierarchy api's (and xml is the most prominent one in my mind)

**Comment by vmuriart** [comment]
I think it would be best to mimic the api of other established libraries (unless the whole point of the library is to establish a new api). The standard library package `xml` uses `getchildren` and so does the popular `lxml`. That being said, no reason why it couldnt have both `.getparent()` and `.parent`

Can you verify [this api](http://lxml.de/api/lxml.etree._Element-class.html) is what you are talking about? I've avoided working with `xml` files thus im not very familiar with its libraries :smiley: 

Would it only be the addition of `getparent()` or would it be better to implement some of the other elements from it? 

I can try to write a `pr` for it, but its upto @andialbrecht if he wants to implement.

**Comment by vmuriart** [comment]
then again [bs4](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) api is very nice too...

**Comment by andialbrecht** [comment]
@vmuriart it's definitely not the intention to establish a new api. Or, to be more precise, sqlparse got stuck to 0.1.x (for years now :grin:) because I started with a _very_ minimal API: officially documented is only `sqlparse.split`, `sqlparse.format` and `sqlparse.parse` :smile: 

So I welcome those ideas here in this thread to find a good API for inspecting a parsed statement!

**Comment by thorsummoner** [comment]
I personally think the xml api in python is unsavory. bs4's api would probably be much nicer (and more pythonic maybe). 

Here is a snippet of the bs4 doc's nav:
```
Navigating the tree
  Going down
    Navigating using tag names
    .contents and .children
    .descendants
    .string
    .strings and stripped_strings
  Going up
    .parent
    .parents
  Going sideways
    .next_sibling and .previous_sibling
    .next_siblings and .previous_siblings
  Going back and forth
    .next_element and .previous_element
    .next_elements and .previous_elements
```
These properties sound pretty reasonable to me, with the possible exception of the navigation by tag name, which I imagine for sql could look something like:

    query.where[2].orderby

Which might evaluate as the third where clause's order keyword object (ASC, DESC). 

But I hesitate to say its something to demand as I'm not sure sql's structure lends to consistent name navigation; but the sql parser engine author could probably speak better to that effect.

---

Bs4 also declares the `.string` property to be the canonical way to get a (unicode) object of the node's text. That may conflict with the existing api which IIRC has a getter/property named something verbose.

:twocents:

**Comment by vmuriart** [comment]
@bc-lee it suddenly hit me what you meant with this. I made and necessary corrections. Below is the new output. Please met us know if this didn't fix it, and re-open the issue.

```python
from __future__ import print_function
import sqlparse


sql = "CREATE TABLE test();"
stmt = sqlparse.parse(sql)[0]

for item in stmt.tokens:
    print("Type: {:34} ttype: {:21} Parent: {:20} has_ancestor: {}".format(
        type(item), item.ttype, item.parent, item.has_ancestor(stmt)))

Type: <class 'sqlparse.sql.Token'>       ttype: Token.Keyword.DDL     Parent: CREATE TABLE test(); has_ancestor: True
Type: <class 'sqlparse.sql.Token'>       ttype: Token.Text.Whitespace Parent: CREATE TABLE test(); has_ancestor: True
Type: <class 'sqlparse.sql.Token'>       ttype: Token.Keyword         Parent: CREATE TABLE test(); has_ancestor: True
Type: <class 'sqlparse.sql.Token'>       ttype: Token.Text.Whitespace Parent: CREATE TABLE test(); has_ancestor: True
Type: <class 'sqlparse.sql.Identifier'>  ttype: None                  Parent: CREATE TABLE test(); has_ancestor: True
Type: <class 'sqlparse.sql.Parenthesis'> ttype: None                  Parent: CREATE TABLE test(); has_ancestor: True
Type: <class 'sqlparse.sql.Token'>       ttype: Token.Punctuation     Parent: CREATE TABLE test(); has_ancestor: True
```
