### ISSUE TITLE
Link from pypi page to docs is broken

### ISSUE THREAD

**Issue by guettli** [andialbrecht/sqlparse#234]
Hi,

the link from the pypi page to the docs leads to an old link:

pypi: https://pypi.python.org/pypi/sqlparse

http://pythonhosted.org/sqlparse/

> sqlparse's documentation is hosted on Read The Docs. You will be redirected to the new documentation within 10 seconds. If the browser does not automatically redirect you, you may want to go to the destination manually. 

Not important, but updating the link would be nice. Thank you.

**Comment by andialbrecht** [comment]
hm... looks like that this is not possible ATM: https://bitbucket.org/pypa/pypi/issues/24/allow-deleting-project-documentation-from

**Comment by guettli** [comment]
My ideas was to update the pypi page to point to the new location.

Yes, you are right, deleting the docs from pythonhosted.org would be nice, too.

**Comment by andialbrecht** [comment]
In fact, I don't know how to remove the link on the pypi page ;)

Thomas Güttler <notifications@github.com> schrieb am Mi., 4. Mai 2016 um
17:55 Uhr:

**Comment by guettli** [comment]
... me, too. I don't know how to change this data. I thought this data gets created from data in setup.py. But in your setup.py the term "pythonhosted" does not appear.

I have no clue.

**Comment by vmuriart** [comment]
Apparently you need to upload a html page to it?
https://github.com/python-diamond/Diamond/issues/54
 or 
http://stackoverflow.com/questions/6521931/how-to-delete-documentation-from-pypi

**Comment by andialbrecht** [comment]
@vmuriart that's what I did actually. On pythonhosted is a simple HTML page that redirects to Read The Docs.

Closing this issue as there seems to be no way to remove the documentation link from PyPI again or providing a direct link to Read The Docs on PyPI.

**Comment by vmuriart** [comment]
There is now an option to `Destroy Documentation` in [Pypi](http://stackoverflow.com/a/41856147/5208670).

**Comment by andialbrecht** [comment]
Done ;)

**Comment by guettli** [comment]
thank you
