### ISSUE TITLE
Add extension .py to bin/sqlparse

### ISSUE THREAD

**Issue by vmuriart** [andialbrecht/sqlparse#247]
Windows doesn't do `shebang`. It would expand usage.
For example: https://github.com/Glavin001/atom-beautify/issues/456

**Comment by andialbrecht** [comment]
Maybe we can move this script into the package and add it as an [console_script entry point](http://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point). This should work on all systems.

**Comment by vmuriart** [comment]
same as #220
