### ISSUE TITLE
Prepare next release?

### ISSUE THREAD

**Issue by vmuriart** [andialbrecht/sqlparse#257]
Master branch has had quite a few bug fixes and some minor new features added without changing much of it's previous behavior. It's probably at a good point to be ahead and prepare it for a release.

Anything pending for packaging next release? 

Anything pending for packaging release under `0.2.0` instead of `0.1.20`?
Ideally I would like to include fixes for #168 and #256 if you go with `0.2.0`.

**Comment by vmuriart** [comment]
Part of the motivation behind this is that most of the upstream changes I haven't applied change the grouping behavior and adds various sub-groupings which changes the overall parsing. I would rather that be it's own separate release in case it introduces any issues.

**Comment by andialbrecht** [comment]
IMO it's time to make a 0.2.0 release. But I'd rather not include #256. I think we still need some discussions how the API should look like and of course some testing.

**Comment by vmuriart** [comment]
Sounds good! Agree on #256, there's a few corner cases that keep biting me and haven't figured out the "expected" behavior on them.
Test out the entry-scripts work for your machine, I had difficulty running it on `travis` but ran fine on my dev machine and test machine.

**Comment by andialbrecht** [comment]
@vmuriart, do you have any changes you'd like to see in 0.2.0? Otherwise I'd be happy to release 0.2.0 this weekend ;)

**Comment by vmuriart** [comment]
I'm good as well for 0.2.0. We may need to update the documentation to
reflect some the new options, but that can be done post release as well.

It's time to set `0.2.0` free.

**Comment by darikg** [comment]
bump - any timeline on a 0.2.0 release?

**Comment by andialbrecht** [comment]
Sorry, I was busy the last weeks. But I'll have a lot of free time next week to do the release.

**Comment by andialbrecht** [comment]
Done. 0.2.0 is available on PyPI. Many thanks to all contributors!
