### ISSUE TITLE
can not find sqlformat

### ISSUE THREAD

**Issue by aicochow** [andialbrecht/sqlparse#259]
when I run `where sqlformat`,can not find path.
when I run `where sqlparse` ,I can find the path.

**Comment by vmuriart** [comment]
which version are you using?

**Comment by vmuriart** [comment]
and operating system? 
This should be solved in the next release.

**Comment by aicochow** [comment]
os:windows 7 pro
sqlparse version:the newest version

**Comment by john-ro** [comment]
I'm on a Mac using 0.2.0.dev0.

Is there a workaround for this?

**Comment by vmuriart** [comment]
`0.2.0dev0` is the generic name (AFAIK) that we been using for the development branch. So it incorporates quite a few commits, some of which changed the executable.

I suspect you install it in development `pip install -e .` and been pulling the latest commits? If so try reinstalling it. `setup.py` changed the location of the script

**Comment by vmuriart** [comment]
@aicochow by latest version do you mean latest released in [Pypi](https://pypi.python.org/pypi/sqlparse) ?

**Comment by aicochow** [comment]
@vmuriart yes

**Comment by vmuriart** [comment]
@aicochow I just re-read your first comment and realized what's going on. I accidentally renamed the command `sqlparse` instead of `sqlformat`.

I just committed the change to fix this https://github.com/andialbrecht/sqlparse/commit/c41f200ac5d2f376a733e3bc2feb15c8ca658c00#diff-2eeaed663bd0d25b7e608891384b7298

**Comment by aicochow** [comment]
Traceback (most recent call last): File "C:\Program Files\Python35-32\Scripts\sqlformat-script.py", line 9, in load_entry_point('sqlparse==0.2.0.dev0', 'console_scripts', 'sqlformat')() File "C:\Program Files\Python35-32\lib\site-packages\sqlparse-0.2.0.dev0-py3.5.egg\sqlparse\cli.py", line 137, in main UnicodeDecodeError: 'cp932' codec can't decode byte 0x83 in position 297: illegal multibyte sequence

**Comment by vmuriart** [comment]
This looks to be a different issue altogether. Looks like the initial bug you reported here is working.
Would be best if you open a new ticket for documentation purposes. 

That being said, its an encoding error :sob: can you post a sample of the text you are trying?

**Comment by aicochow** [comment]
I am sorry
I change `LF` to `CRLF`,then it works.
thank you

**Comment by vmuriart** [comment]
:+1: @aicochow thanks for reporting that though. It shouldn't have faulted, and I think I see why it faulted.
