### ISSUE TITLE
Change in grouping behaving with hanging schema qualifier on master?

### ISSUE THREAD

**Issue by darikg** [andialbrecht/sqlparse#261]
On 0.1.19:

```
In [4]: sqlparse.parse('SELECT * FROM foo.')[0].tokens
Out[4]:
[<DML 'SELECT' at 0x544a188>,
 <Whitespace ' ' at 0x544a0e8>,
 <Wildcard '*' at 0x544a1d8>,
 <Whitespace ' ' at 0x544a228>,
 <Keyword 'FROM' at 0x544a278>,
 <Whitespace ' ' at 0x544a2c8>,
 <Identifier 'foo.' at 0x543af48>]
```

On master:
```
In [3]: sqlparse.parse('SELECT * FROM foo.')[0].tokens
Out[3]:
[<DML 'SELECT' at 0x55E94A8>,
 <Whitespace ' ' at 0x55E9548>,
 <Wildcard '*' at 0x55E9598>,
 <Whitespace ' ' at 0x55E95E8>,
 <Keyword 'FROM' at 0x55E9638>,
 <Whitespace ' ' at 0x55E9688>,
 <Identifier 'foo' at 0x5641868>,
 <Punctuation '.' at 0x55E9728>]
```

Notice that on master the punctuation isn't grouped with the `foo` identifier.

I think the former behavior is correct, even though it's not valid sql.

**Comment by darikg** [comment]
btw I'm happy to submit a PR to change this, just wanted to make sure you guys agreed or not on what the correct behavior is

**Comment by vmuriart** [comment]
@darikg https://github.com/andialbrecht/sqlparse/commit/1e770d9b99983fa82375b71c5b3f5d8c6bb1a72e is the commit that changed the behavior. 

Personally I don't have strong feeling either way for it. Since it is invalid sql there isn't a proper "expected" behavior. I didn't want to add extra code to handle it's erratic behavior. 

A similar case can be made for sql statements that have un-matched parenthesis/brackets and how these should be handled. `select 1 + (2 + (3 + 4) from dual`

what's your reasoning for the former to be the preferred behavior?

**Comment by vmuriart** [comment]
I have the changes ready https://github.com/andialbrecht/sqlparse/commit/1e770d9b99983fa82375b71c5b3f5d8c6bb1a72e to push. Since this was the old behavior, I don't mind resetting it back.

**Comment by vmuriart** [comment]
A better example I should have made would have been `select 1 from dual where 5 <`

**Comment by darikg** [comment]
At pgcli we use sqlparse as the basis for code completion suggestions. So 'select * from foo.b' means suggest tables beloning to schema foo that start with 'b'. This generalizes nicely to the empty case 'select * from foo.' which should mean suggest all tables from schema foo. 

You're totally right about the analogous case with dangling comparisons but I don't think that impacts us either way :)

**Comment by vmuriart** [comment]
Makes sense. I've applied the patch, so it should be back to it's old behavior.

**Comment by darikg** [comment]
Great! Here's another similar case: `SELECT foo. FROM foo`

Even with your recent changes, the punctuation isn't being grouped with the identifier.

Master:
```
In [47]:  sqlparse.parse('SELECT foo. FROM foo')[0].tokens
Out[47]:
[<DML 'SELECT' at 0x5844048>,
 <Whitespace ' ' at 0x5844098>,
 <Identifier 'foo' at 0x583ACE0>,
 <Punctuation '.' at 0x5844138>,
 <Whitespace ' ' at 0x5844188>,
 <Keyword 'FROM' at 0x58441D8>,
 <Whitespace ' ' at 0x5844228>,
 <Identifier 'foo' at 0x583AD48>]
```

0.1.19:
```
In [5]: sqlparse.parse('SELECT foo. FROM foo')[0].tokens
Out[5]:
[<DML 'SELECT' at 0x53b3c28>,
 <Whitespace ' ' at 0x53b3c78>,
 <Identifier 'foo.' at 0x5394848>,
 <Whitespace ' ' at 0x53b3d68>,
 <Keyword 'FROM' at 0x53b3db8>,
 <Whitespace ' ' at 0x53b3e08>,
 <Identifier 'foo' at 0x53949c8>]
```

**Comment by vmuriart** [comment]
@darikg thanks for pointing that out. I added it to the tests and pushed the fix for it.

**Comment by darikg** [comment]
Great, thanks! I got all of our tests to pass now :100:

**Comment by vmuriart** [comment]
Hopefully you didn't have to change any tests to accommodate for any changes here. I'll go ahead and close the issue.
