### ISSUE TITLE
Backticks in MySQL identifiers

### ISSUE THREAD

**Issue by phdru** [andialbrecht/sqlparse#272]
```python
print parse("INSERT INTO table (id, name) VALUES (1, 'one')")[0].tokens
print parse("INSERT INTO `table` (id, name) VALUES (1, 'one')")[0].tokens
```
produces
```
[<DML 'INSERT' at 0xB715E5F4>, <Whitespace ' ' at 0xB715E61C>, <Keyword 'INTO' at 0xB715E644>, <Whitespace ' ' at 0xB715E66C>, <Keyword 'table' at 0xB715E694>, <Whitespace ' ' at 0xB715E6BC>, <Parenthesis '(id, n...' at 0xB7153FB4>, <Whitespace ' ' at 0xB715E7D4>, <Keyword 'VALUES' at 0xB715E7FC>, <Whitespace ' ' at 0xB715E824>, <Parenthesis '(1, 'o...' at 0xB716402C>]
[<DML 'INSERT' at 0xB715E9DC>, <Whitespace ' ' at 0xB715EA04>, <Keyword 'INTO' at 0xB715EA2C>, <Whitespace ' ' at 0xB715EA54>, <Function '`table...' at 0xB7164224>, <Whitespace ' ' at 0xB715EBBC>, <Keyword 'VALUES' at 0xB715EBE4>, <Whitespace ' ' at 0xB715EC0C>, <Parenthesis '(1, 'o...' at 0xB716410C>]
```
The difference is Keyword 'table' vs Function '\`table...'

Is it a bug, or sqlparse doesn't support backticks in identifiers?

**Comment by vmuriart** [comment]
It should recognize it based on [these lines](https://github.com/andialbrecht/sqlparse/blob/master/sqlparse/keywords.py#L36-L37). What is your expected result from your example? 

on a side note, doing `parse('select 1 from dual')[0]._pprint_tree()` gives you a better view of the parse results for easier troubleshooting :smile:

**Comment by phdru** [comment]
@vmuriart I wouldn't expect any major difference beteween `insert into table (id, name)` and ```insert into `table` (`id`, `name`)``` (except for Punctuation, of course). But instead I've got:
```
 0 DML 'insert'
 1 Whitespace ' '
 2 Keyword 'into'
 3 Whitespace ' '
 4 Keyword 'table'
 5 Whitespace ' '
 6 Parenthesis '(id, n...'
```
for the first query and
```
 0 DML 'insert'
 1 Whitespace ' '
 2 Keyword 'into'
 3 Whitespace ' '
 4 Function 'table ...'
 |  0 Identifier 'table'
 |  |  0 Name 'table'
 |  1 Whitespace ' '
 |  2 Parenthesis '(id, n...'
```
for the second.

**Comment by phdru** [comment]
Oops, got it. `table` is a keyword. Using `test` instead I've got:
```
 0 DML 'insert'
 1 Whitespace ' '
 2 Keyword 'into'
 3 Whitespace ' '
 4 Function 'test (...'
 |  0 Identifier 'test'
 |  |  0 Name 'test'
 |  1 Whitespace ' '
 |  2 Parenthesis '(id, n...'
```
Uhoo :-( This time it is also a function. I would expect an Identifier and Parenthesis, but not a function.

**Comment by phdru** [comment]
Well, at least sqlparse allows backticks.

**Comment by vmuriart** [comment]
that is a separate bug altogether and one I suspected you were seeing (but pprint made it easier to see :+1: ). I'm trying to figure that one out; its a side effect from allowing user-defined functions.
