### ISSUE TITLE
Passing a stream to sqlparse.parse(stream) broke between 0.1.19 and 0.2.0

### ISSUE THREAD

**Issue by gmccreight** [andialbrecht/sqlparse#273]
I extracted a failing test case here: https://github.com/gmccreight/sqlparse/commit/1cb94246640ac5583f73511d7a47240340a1e583

Is that enough to go on?

Please let me know if you'd like me to provide any additional background or explanation.

Thanks!

**Comment by andialbrecht** [comment]
Thanks for the test case! It's absolutely enough for me to fix this.

**Comment by andialbrecht** [comment]
BTW, feel free to open a pull request for the test.

**Comment by gmccreight** [comment]
Great!  I've added a pull request: https://github.com/andialbrecht/sqlparse/pull/274 .  Thanks so much!
