### ISSUE TITLE
django-debug-toolbar compatibility

### ISSUE THREAD

**Issue by crowlz11** [andialbrecht/sqlparse#275]
Apologies if this has been addressed elsewhere, I have been unable to find anything. As of the 0.2.0 release sqlparse is no longer compatible with django-debug-toolbar. I can't find anything in the changelog that indicates why. Any help would be much appreciated!

**Comment by andialbrecht** [comment]
Thanks for reporting! I'm able to reproduce this.

**Comment by andialbrecht** [comment]
Yepp, there is an undocumented change in some sqlparse internals. the sqlparse. I've added it to the release notes. However, debug_toolbar has adopted the new changes already: https://github.com/django-debug-toolbar/django-debug-toolbar/issues/852

**Comment by vmuriart** [comment]
hmm... was this fixed? I took a quick look at their solution and seemed to hard code it to `0.1.19` I'd rather fix the underlying issue though :confused:

**Comment by andialbrecht** [comment]
The actual change in debug_toolbar is here: https://github.com/dirtycoder/django-debug-toolbar/commit/ea7758a13b8b8e89cad287312a230e1f16cd01d9

**Comment by crowlz11** [comment]
Thank you so much for the help!
