### ISSUE TITLE
sqlparse.split() splits this postgres function in half

### ISSUE THREAD

**Issue by dequis** [andialbrecht/sqlparse#277]
```sql
CREATE FUNCTION htmlent(inp text) RETURNS text
    LANGUAGE plpgsql
    AS $_$
DECLARE
  str text;
BEGIN
str= regexp_replace(quote_literal(inp)
                    ,$$&#(\d+);$$
    ,$$'||chr(\1)||'$$ 
    ,'g');
execute 'select '||str into str;
return str;
END
$_$;
```

```python
>>> text = open("test.sql").read()
>>> formatted = sqlparse.format(text, strip_comments=True, strip_whitespace=True)
>>> split = sqlparse.split(formatted)
>>> len(split)
2
>>> split[0]
'CREATE FUNCTION htmlent(inp text) RETURNS text LANGUAGE plpgsql AS $_$ DECLARE str text; BEGIN str= regexp_replace(quote_literal(inp) ,$$&#(\\d+);'
>>> split[1]
"$$ ,$$'||chr(\\1)||'$$ ,'g'); execute 'select '||str into str; return str; END $_$;"
```

(I didn't write that sql function, i'm just trying to use sqlparse to import it from a legacy system into a new thing. The rest of the ~700kb sql dump imported without issues)

**Comment by vmuriart** [comment]
on each statement can you run ` split[0]._pprint_tree()` and post the output here?

**Comment by dequis** [comment]
```python
>>> parsed = sqlparse.parse(formatted)
>>> len(parsed)
2
>>> parsed[0]._pprint_tree()
 | 0 DDL 'CREATE'
 | 1 Whitespace ' '
 | 2 Keyword 'FUNCTI...'
 | 3 Whitespace ' '
 +-4 Function 'htmlen...'
   +-0 Identifier 'htmlent'
     | 0 Name 'htmlent'
   +-1 Parenthesis '(inp t...'
     | 0 Punctuation '('
     +-1 Identifier 'inp'
       | 0 Name 'inp'
     | 2 Whitespace ' '
     | 3 Builtin 'text'
     | 4 Punctuation ')'
 | 5 Whitespace ' '
 | 6 Keyword 'RETURNS'
 | 7 Whitespace ' '
 | 8 Builtin 'text'
 | 9 Whitespace ' '
 | 10 Keyword 'LANGUA...'
 | 11 Whitespace ' '
 +-12 Identifier 'plpgsq...'
   | 0 Name 'plpgsql'
   | 1 Whitespace ' '
   | 2 Keyword 'AS'
   | 3 Whitespace ' '
   | 4 Builtin '$_$'
 | 13 Whitespace ' '
 | 14 Keyword 'DECLARE'
 | 15 Whitespace ' '
 +-16 Identifier 'str'
   | 0 Name 'str'
 | 17 Whitespace ' '
 | 18 Builtin 'text'
 | 19 Punctuation ';'
 | 20 Whitespace ' '
 | 21 Keyword 'BEGIN'
 | 22 Whitespace ' '
 +-23 Comparison 'str= r...'
   +-0 Identifier 'str'
     | 0 Name 'str'
   | 1 Comparison '='
   | 2 Whitespace ' '
   +-3 Identifier 'regexp...'
     | 0 Name 'regexp...'
 | 24 Punctuation '('
 +-25 Function 'quote_...'
   +-0 Identifier 'quote_...'
     | 0 Name 'quote_...'
   +-1 Parenthesis '(inp)'
     | 0 Punctuation '('
     +-1 Identifier 'inp'
       | 0 Name 'inp'
     | 2 Punctuation ')'
 | 26 Whitespace ' '
 | 27 Punctuation ','
 | 28 Builtin '$$'
 | 29 Operator '&#'
 +-30 Parenthesis '(\d+)'
   | 0 Punctuation '('
   | 1 Error '\'
   +-2 Identifier 'd+'
     | 0 Name 'd'
     | 1 Operator '+'
   | 3 Punctuation ')'
 | 31 Punctuation ';'
>>>
>>>
>>> parsed[1]._pprint_tree()
 | 0 Builtin '$$'
 | 1 Whitespace ' '
 | 2 Punctuation ','
 | 3 Builtin '$$'
 | 4 Single ''||chr...'
 | 5 Builtin '$$'
 | 6 Whitespace ' '
 | 7 Punctuation ','
 | 8 Single ''g''
 | 9 Punctuation ')'
 | 10 Punctuation ';'
 | 11 Whitespace ' '
 | 12 Keyword 'execute'
 | 13 Whitespace ' '
 | 14 Single ''selec...'
 | 15 Operator '||'
 +-16 Identifier 'str'
   | 0 Name 'str'
 | 17 Whitespace ' '
 | 18 Keyword 'into'
 | 19 Whitespace ' '
 +-20 Identifier 'str'
   | 0 Name 'str'
 | 21 Punctuation ';'
 | 22 Whitespace ' '
 | 23 Keyword 'return'
 | 24 Whitespace ' '
 +-25 Identifier 'str'
   | 0 Name 'str'
 | 26 Punctuation ';'
 | 27 Whitespace ' '
 | 28 Keyword 'END'
 | 29 Whitespace ' '
 | 30 Builtin '$_$'
 | 31 Punctuation ';'
```

**Comment by vmuriart** [comment]
Not very familiar with Postgres, but I think I see what's going on. Is "$$"
an open/close token in Postgres ?

**Comment by dequis** [comment]
Yeah, https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING

It's also used by the function (`$_$`), which is the part that certainly works, so it's nesting two different dollar-quoting levels.

**Comment by vmuriart** [comment]
Is token_list `parsed[0]._pprint_tree()[12]` right? it should take more than just `$_$` at position 4 right?

**Comment by vmuriart** [comment]
hold up, disregard my last comment. I just realized that it may be a separate issue from the one you reported since its a different section of the code that handles it.

**Comment by andialbrecht** [comment]
ah, reading the PostgreSQL specification currently sqlparse handles the dollar quoting not as properly as it should be.

**Comment by dequis** [comment]
I have some functions in this sql file written in tcl (`LANGUAGE pltcl` and `pltclu`), those should definitely be literal strings.

```sql
CREATE FUNCTION replace_quote_quote(character varying) RETURNS character varying
    LANGUAGE pltcl IMMUTABLE
    AS $_$
        set param $1
        set ret [regsub -all {''} $param {"}]
        return $ret
$_$;
```

sqlparse handles this one decently enough, but that was probably just luck.

```python
>>> sqlparse.parse(sqlparse.format(a, strip_whitespace=True))[0]._pprint_tree()
 0 DDL 'CREATE'
 1 Whitespace ' '
 2 Keyword 'FUNCTI...'
 3 Whitespace ' '
 4 Function 'replac...'
 |  0 Identifier 'replac...'
 |  |  0 Name 'replac...'
 |  1 Parenthesis '(chara...'
 |  |  0 Punctuation '('
 |  |  1 Builtin 'charac...'
 |  |  2 Whitespace ' '
 |  |  3 Builtin 'varying'
 |  |  4 Punctuation ')'
 5 Whitespace ' '
 6 Keyword 'RETURNS'
 7 Whitespace ' '
 8 Builtin 'charac...'
 9 Whitespace ' '
10 Builtin 'varying'
11 Whitespace ' '
12 Keyword 'LANGUA...'
13 Whitespace ' '
14 Identifier 'pltcl'
 |  0 Name 'pltcl'
15 Whitespace ' '
16 Keyword 'IMMUTA...'
17 Whitespace ' '
18 Keyword 'AS'
19 Whitespace ' '
20 Builtin '$_$'
21 Whitespace ' '
22 Keyword 'set'
23 Whitespace ' '
24 Identifier 'param'
 |  0 Name 'param'
25 Whitespace ' '
26 Placeholder '$1'
27 Whitespace ' '
28 Keyword 'set'
29 Whitespace ' '
30 Identifier 'ret [r...'
 |  0 Name 'ret'
 |  1 Whitespace ' '
 |  2 Identifier '[regsu...'
 |  |  0 Name '[regsu...'
31 Whitespace ' '
32 Keyword 'return'
33 Whitespace ' '
34 Placeholder '$ret'
35 Whitespace ' '
36 Builtin '$_$'
37 Punctuation ';'
```

**Comment by vmuriart** [comment]
@andialbrecht is the concern that we wouldn't be parsing the contents within the `$$` string?
would this be much different than
`select 'select 1 from dual' from dual` not parsing the contents of the string?

**Comment by andialbrecht** [comment]
@dequis the difference between the second and first example is that you use `$$` for quoting a literal string (the regex) in the first example too. The second uses `$$` only for the function body.

@vmuriart right. Syntactically it'd be ok to treat a function body as a literal string in that case. It is actually one. Maybe we should really do a breaking change here and revert this behavior. In fact, it's already a PostgreSQL specific hack in [`statement_splitter.py`](https://github.com/andialbrecht/sqlparse/blob/master/sqlparse/engine/statement_splitter.py#L30-L45).

**Comment by darikg** [comment]
Just my two cents: leaving the function body as a literal string makes a lot of sense. Since postgresql allows functions to be written in arbitrary languages (e.g. python), there's no guarantee sqlparse can parse the body properly anyway.

**Comment by dequis** [comment]
@andialbrecht that pltcl example was just to illustrate what @darikg said much more clearly - there's an attempt to parse that non-sql body that somehow succeeds even with stuff that looks like mismatched quotes to my eyes (`{''} $param {"}`)

Also, since I found this recently, the original source code of these functions used a different quoting style, so this `$_$` stuff is how pg_dump chooses to generate it.

**Comment by andialbrecht** [comment]
FTR, I'm already working on a fix that treats everything in $$ as literal
strings.

dx <notifications@github.com> schrieb am Mi., 10. Aug. 2016 17:15:

**Comment by vmuriart** [comment]
I guess you beat me to it. I think we should be able to handle it on the regex portion of the parsing

**Comment by andialbrecht** [comment]
I don't think so. Treating the whole function body as a literal string
seems to be right. AFAIK it's specific to postgres to allow arbitrary
languages here. So we can't assume that the body is SQL (unless we dig
deeper and evaluate the `LANGUAGE` keyword). In the given example it
shouldn't matter if the function body contains additional `$$` quotings
since the whole thing is already a literal string.

Let me know if you've got an alternative approach!

Vik <notifications@github.com> schrieb am Mi., 10. Aug. 2016 20:57:

**Comment by dequis** [comment]
Thanks! :heart:
