### ISSUE TITLE
Unify naming schema

### ISSUE THREAD

**Issue by T-002** [andialbrecht/sqlparse#283]
Hi andialbrecht,

I am using sqlparse for a data analysis project. It works (nearly) as expected. From my point of view, there is one naming issue that could be adjusted:

```python
type(is_keyword) ==  bool
type(is_group) == method
type(is_whitespace) == method

```
I found it rather confusing having the same naming schema for different invocation. In my opinion there are two valid adjustments you could make:

- *is_keyword* could become a method, or
- you could add the *@property* decorator to *is_group* and *is_whitespace*

From my opinion the second option is preferable.
What do you think about it?

Best regards,

Christian

**Comment by vmuriart** [comment]
I'd be good with the second option. The only concern is that it changes the behavior and might break other users code. @andialbrecht any thoughts? 
I think as long as we include it on the changelog it should be fine.

**Comment by vmuriart** [comment]
I opened a `pr` for this and went with option 3. Make `is_group` and `is_whitespace` properties defined on `__init__`
A simple search and replace fix all usages within `sqlparse`.
