### ISSUE TITLE
Failing on Python 3.6

### ISSUE THREAD

**Issue by vmuriart** [andialbrecht/sqlparse#286]
I've noticed in some of the CI Testing the [tests on python 3.6](https://travis-ci.org/andialbrecht/sqlparse/jobs/154337479) have been failing. Looks like there is some breaking changes coming

**Comment by timgraham** [comment]
Bisected the failures to https://github.com/python/cpython/commit/21b87fec4a3ee19db15dfa85e38fcefd3d79be5e.

**Comment by vmuriart** [comment]
Awesome detective work! thanks. I wonder if the break of some code was expected when they committed the change.

**Comment by andialbrecht** [comment]
Thanks, @timgraham!

**Comment by timgraham** [comment]
Here's a minimal example `test.py` to reproduce:
```python
class _TokenType(tuple):
    parent = None

    def __getattr__(self, name):
        new = _TokenType(self + (name,))
        setattr(self, name, new)
        new.parent = self
        return new

Token = _TokenType()

Keyword = Token.Keyword

class KeywordCaseFilter(object):
    ttype = Keyword
```
```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    class KeywordCaseFilter(object):
TypeError: '_TokenType' object is not callable
```
It's not obvious to me what the issue is. Maybe @ncoghlan can advise.

**Comment by ncoghlan** [comment]
The problem you're hitting is that the given `__getattr__` implementation is returning an answer for `Keyword.__set_name__`:

    >>> Keyword.__set_name__
    ('Keyword', '__set_name__')

That's then the `_TokenType` instance that is being complained about in the error message, rather than `Keyword` itself.

Would you mind filing a usability issue against CPython 3.6 for this? We should be able to provide a better chained TypeError in this case that reports the specific object with the problematic `__set_name__` attribute (rather than just passing along the underlying exception), as well as supporting `__set_name__ = None` to explicitly disable further lookup processing.

**Comment by timgraham** [comment]
Created http://bugs.python.org/issue28214 for the follow up cpython issue requested by Nick.

**Comment by andialbrecht** [comment]
FTR, the segmentation fault that occurs now on the Python 3.6 build seems to be related to py.test itself.

There are three tests, that cause a segfault:
- test_cli.test_script
- test_format.test_format_column_orderung
- test_format.test_truncate_strings

Tests pass when either commenting out those tests or when adding a pytest fixture to the function signature. `_pytest/capture.py", line 98 in activate_funcargs` seems to be the culprit as far as I can tell at the moment.

**Comment by timgraham** [comment]
The tests are passing for me with the latest cpython 3.6 branch. Also, I saw some seg faults when testing Django with older snapshots of 3.6, so it might be a fixed issue.

**Comment by andialbrecht** [comment]
ah, ok. I'll try again with latest 3.6 branch. The issue seems to be related with pytest's `capsys` fixture. For me (Python 3.6.0b1) this minimal test file reproduces the segfault:

```
def test_foo(capsys):
    pass

def test_foo2():
    pass
```

**Comment by andialbrecht** [comment]
I can confirm that it works with cpython from current default branch and 3.5 branch.

**Comment by timgraham** [comment]
cpython fixed backwards-compatibility in https://hg.python.org/cpython/rev/1a2b8398f045/, so my commit for sqlparse can be reverted. Andi, can you revert it or would you like a PR?

**Comment by andialbrecht** [comment]
Thanks for the feedback! I've reverted the commit.

Tim Graham <notifications@github.com> schrieb am Mi., 21. Sep. 2016 um
16:20 Uhr:

**Comment by vmuriart** [comment]
Awesome work @timgraham
