### ISSUE TITLE
License clarification 

### ISSUE THREAD

**Issue by vmuriart** [andialbrecht/sqlparse#288]
Just noticed a small discrepancy in the licensing of `sqlparse`. The (LICENSE/COPYING)(https://github.com/andialbrecht/sqlparse/blob/master/LICENSE) file is the [3-clause BSD License](https://opensource.org/licenses/bsd-license.php). The [headers in each of the files](https://github.com/andialbrecht/sqlparse/blob/master/setup.py#L4-L7) though has a link to the [2-clause BSD License](http://www.opensource.org/licenses/bsd-license.php) instead. 

Is the licensing correct or was the project meant to be released under one of the two licenses.

**Comment by andialbrecht** [comment]
The link in the files is wrong. It should point to the 3-clause BSD license.

Vik <notifications@github.com> schrieb am Di., 30. Aug. 2016 um 17:07 Uhr:
