### ISSUE TITLE
Table names with "$" are split into tokens

### ISSUE THREAD

**Issue by rchateauneu** [andialbrecht/sqlparse#291]
In Oracle, table names can contain the dollar sign "$".
Apparently, sqlparse splits them.

**Comment by vmuriart** [comment]
Which version of sqlparse? 
We made some changes for postgresql on recent commits

**Comment by rchateauneu** [comment]
Version 0.2.1
Query is for example:

SELECT distinct sess.sid, sess.username, sess.schemaname, proc.spid,pid,sess.osuser,sess.machine,sess.process,
	sess.port,proc.terminal,sess.program,proc.tracefile
	  FROM v$session sess,
		   v$process proc
	 WHERE sess.type     = 'USER'
	   and sess.paddr = proc.addr

**Comment by andialbrecht** [comment]
Thanks for reporting!

Fixed in 358ad4b9754721f69c6b40333653bd84edb8634f

**Comment by john-bodley** [comment]
@andialbrecht it seems like Presto and Trino [partitioned tables](https://prestodb.io/docs/current/release/release-0.199.html) now ... 

> have a hidden system table that contains the partition values. A table named example will have a partitions table named example$partitions. This provides the same functionality and data as SHOW PARTITIONS.

however https://github.com/andialbrecht/sqlparse/commit/358ad4b9754721f69c6b40333653bd84edb8634f fails to parse this correctly if the schema is provided, i.e., (using `sqlparse` 0.4.3),

```python
from sqlparse import parse
stmt = parse("SELECT * FROM foo.bar$partitons")[0]
stmt._pprint_tree()
```

returns 

```|- 0 DML 'SELECT'
|- 1 Whitespace ' '
|- 2 Wildcard '*'
|- 3 Whitespace ' '
|- 4 Keyword 'FROM'
|- 5 Whitespace ' '
|- 6 Identifier 'foo.bar'
|  |- 0 Name 'foo'
|  |- 1 Punctuation '.'
|  `- 2 Name 'bar'
|- 7 Error '$'
`- 8 Identifier 'partit...'
   `- 0 Name 'partit...'
```

whereas sans schema, i.e., 

```python
from sqlparse import parse
stmt = parse("SELECT * FROM bar$partitons")[0]
stmt._pprint_tree()
```
 
correctly (per https://github.com/andialbrecht/sqlparse/commit/358ad4b9754721f69c6b40333653bd84edb8634f) returns,

```|- 0 DML 'SELECT'
|- 1 Whitespace ' '
|- 2 Wildcard '*'
|- 3 Whitespace ' '
|- 4 Keyword 'FROM'
|- 5 Whitespace ' '
`- 6 Identifier 'bar$pa...'
   `- 0 Name 'bar$pa...'
```

**Comment by john-bodley** [comment]
@andialbrecht please ignore my previous comment. The parser handles the `$partition` suffix correctly when double quoting the hidden system table.
