### ISSUE TITLE
"UNION ALL" parsed as two tokens

### ISSUE THREAD

**Issue by rchateauneu** [andialbrecht/sqlparse#294]
In a SQL query, the operator "UNION ALL" is parsed as two different keywords:
Example:
SELECT Txn_Date FROM Store_Information
UNION ALL
SELECT Txn_Date FROM Internet_Sales

On the contrary, keywords such as "LEFT OUTER JOIN", "FULL JOIN", "FULL OUTER JOIN", "INNER JOIN" are parsed as one keyword (ttype = Token.Keyword) only.

Is it intended please, and if so, what is the rationale behind it ?

Same problem for "GROUP BY" which as parsed as two separate keywords.

**Comment by andialbrecht** [comment]
Thanks for reporting!
