### ISSUE TITLE
sqlparse parse sql incorrect

### ISSUE THREAD

**Issue by chengchong010** [andialbrecht/sqlparse#306]
code:
    stmt = sqlparse.parse(sql)[0]
    print stmt._pprint_tree()

1)sql one:
select * from mxt_kb_knowledge where name='y' and xstate='normal'    \
and check_state='accepted' and sync_state = 'synchronized' and (expire_date is null or exp
ire_date > sysdate()) and (valid_date is null or valid_date < sysdate()) limit 1

test result:  
The "xstate = 'normal'" as same level as "name='y'"

 8 Where 'where ...'
 |  0 Keyword 'where'
 |  1 Whitespace ' '
 |  2 Comparison 'name='...'
 |  |  0 Identifier 'name'
 |  |  |  0 Name 'name'
 |  |  1 Comparison '='
 |  |  2 Single "'y'"
 |  3 Whitespace ' '
 |  4 Keyword 'and'
 |  5 Whitespace ' '
 |  6 Comparison 'xstate...'  <-----------------------
 |  |  0 Identifier 'xstate'
 |  |  |  0 Name 'xstate'
 |  |  1 Comparison '='
 |  |  2 Single ''norma...'
 |  7 Whitespace ' '
 |  8 Keyword 'and'
 |  9 Whitespace ' '
 | 10 Comparison 'check_...'
 |  |  0 Identifier 'check_...'
 |  |  |  0 Name 'check_...'
 |  |  1 Comparison '='
 |  |  2 Single ''accep...'
 | 11 Whitespace ' '

2)sql two:  
modify the "xstate='normal'"  to "state='normal'"

select * from mxt_kb_knowledge where name='y' and state='normal'    \
and check_state='accepted' and sync_state = 'synchronized' and (expire_date is null or exp
ire_date > sysdate()) and (valid_date is null or valid_date < sysdate()) limit 1

test result:  the "state='normal'" is not same level as "name='y'"

 8 Where 'where ...'
 |  0 Keyword 'where'
 |  1 Whitespace ' '
 |  2 Comparison 'name='...'
 |  |  0 Identifier 'name'
 |  |  |  0 Name 'name'
 |  |  1 Comparison '='
 |  |  2 Single "'y'"
 |  3 Whitespace ' '
 |  4 Keyword 'and'
 |  5 Whitespace ' '
 |  6 Keyword 'state'  <---------------------
 |  7 Comparison '='
 |  8 Single ''norma...'
 |  9 Whitespace ' '
 | 10 Keyword 'and'
 | 11 Whitespace ' '

what happened?

**Comment by vmuriart** [comment]
this is related to #296. state is being treated as a keyword. Looks like Andi is already working on it.

**Comment by andialbrecht** [comment]
See #296
