### ISSUE TITLE
Square brackets in where clause

### ISSUE THREAD

**Issue by jkbbwr** [andialbrecht/sqlparse#309]
```
select 1 from a where b[c][d] = 3
```

Causes the `Comparison` to not form properly. It also doesn't emit `Identifier` of `b[c][d]` it instead emits them as three separate tokens.

**Comment by andialbrecht** [comment]
What SQL dialect is this? I've never seen the notation `b[c][d]` yet.

**Comment by jkbbwr** [comment]
We are trying to grow a home grown extension on top of standard SQL allowing for chaining of `[x]` onto a column. I just noticed that `b.[c]` parses correctly but `b.[c][d]` doesn't it only parses `b.[c].[d]`

Very weirdly though `b[c].[d]` works fine.

Got any input?

**Comment by andialbrecht** [comment]
Thank you for the feedback. The use cases where it parses correctly seem to match (more or less) the MS-SQL definition on how to use square brackets ([example](https://technet.microsoft.com/en-us/library/ms176027(v=sql.105).aspx#Anchor_1)). 

In fact, it's a bit weird that it also parses `b[c].[d]`. I don't think that handling of `b[c][d]` is common enough to add this feature to sqlparse.

**Comment by jkbbwr** [comment]
Fair play. We will probably implement a higher level work around then drop support for sqlparse internally. Thanks for your time and engagement.

**Comment by andialbrecht** [comment]
FIY, a workaround could be to inject a custom regex somewhere around this line after importing sqlparse: https://github.com/andialbrecht/sqlparse/blob/master/sqlparse/keywords.py#L68

I've never tried it, but it seems that you have to re-process the SQL_REGEX constant found in this module too (line 88).

Hope that helps ;)
