### ISSUE TITLE
`sqlformat` cannot handle Unicode characters

### ISSUE THREAD

**Issue by twang2218** [andialbrecht/sqlparse#315]
Here is the SQL contains Unicode characters:

```sql
SELECT *
                FROM User
        WHERE name = '大圣'
```

After `sqlformat` the characters are scrambled:

```bash
$ sqlformat dump.sql --reindent
SELECT *
FROM User
WHERE name = 'å¤§å£'
```

I installed `sqlformat` by `pip install sqlparse`, and version is `0.2.2`:

```bash
$ sqlformat --version
0.2.2

**Comment by twang2218** [comment]
Also need to mention, I found the problem when using Atom, and there are other people have the same issues:

* https://github.com/Glavin001/atom-beautify/issues/1094
* https://github.com/Glavin001/atom-beautify/issues/1142

**Comment by twang2218** [comment]
The problem can also repeatable in the python cli:

```python
>>> import sqlparse
>>> with open('dump.sql', 'r') as sqlfile:
...   sql=sqlfile.read()
...
>>> print sql
SELECT *
                FROM User
        WHERE name = '大圣'

>>> print sqlparse.format(sql)
SELECT *
                FROM User
        WHERE name = 'å¤§å£'
```

**Comment by twang2218** [comment]
After some digging, I found that if I specified the `encoding` in the python script, the result will be correct:

```python
>>> print sqlparse.format(sql, encoding='utf8')
SELECT *
                FROM User
        WHERE name = '大圣'
```

And I followed the source code found at <https://github.com/andialbrecht/sqlparse/blob/master/sqlparse/lexer.py#L50>:

```python
            try:
                text = text.decode()
            except UnicodeDecodeError:
                if not encoding:
                    encoding = 'unicode-escape'
                text = text.decode(encoding)
```

And I tried with `unicode-escape`, it got the same scrambled characters:

```python
 print sqlparse.format(sql, encoding='unicode-escape')
SELECT *
                FROM User
        WHERE name = 'å¤§å£'
```

**Comment by twang2218** [comment]
And there is no way to specify the encoding on CLI for now.

**Comment by twang2218** [comment]
On my macOS, I temporarily fixed the issue by the following command:

```bash
sed -i -e 's/unicode-escape/utf-8/' /usr/local/lib/python2.7/site-packages/sqlparse/lexer.py
```

which replace `unicode-escape` with `utf-8` in the `lexer.py` file.

**Comment by vmuriart** [comment]
Unicode will be the death of me... 😦 
I'll need to get a refresher on what was the latest changes we did for it. The temporary fix though could be to add a `cli` option to specify encoding. Do you know if there is a popular `-option` that is already being used on other applications?

**Comment by twang2218** [comment]
Most other beautifier just use `utf-8` as default encoding, or use the system default encoding. I think `utf-8` is the most common approach, although I'm not sure why `unicode-escape` here, maybe @phdru can tell more.

And for the CLI option, how about `--encoding`?

**Comment by phdru** [comment]
I preserved `unicode-escape` from the previous version of the code which wasn't mine.

**Comment by twang2218** [comment]
@phdru oh, I'm sorry, it is from previous version.

I'm still trying to understand why `unicode-escape`, if I'm right this time, it's introduced in PR https://github.com/andialbrecht/sqlparse/pull/88 

```diff
-            text = text.decode(self.encoding)
+            try:
+                text = text.decode(self.encoding)
+            except UnicodeDecodeError:
+                text = text.decode('unicode-escape')
```

And the test case was added in commit https://github.com/andialbrecht/sqlparse/commit/7088a29fc330dd806e56fb4f7af0f9389bcb114a

```python
def test_parse_sql_with_binary():
    # See https://github.com/andialbrecht/sqlparse/pull/88
    digest = '\x82|\xcb\x0e\xea\x8aplL4\xa1h\x91\xf8N{'
    sql = "select * from foo where bar = '{0}'".format(digest)
    formatted = sqlparse.format(sql, reindent=True)
    tformatted = "select *\nfrom foo\nwhere bar = '{0}'".format(digest)
    if PY2:
        tformatted = tformatted.decode('unicode-escape')
    assert formatted == tformatted
```

By replacing `unicode-escape` with `utf-8` in `lexer.py` will cause this test case fail.

```bash
input = "select * from foo where bar = '\x82|\xcb\x0e\xea\x8aplL4\xa1h\x91\xf8N{'", errors = 'strict'

    def decode(input, errors='strict'):
>       return codecs.utf_8_decode(input, errors, True)
E       UnicodeDecodeError: 'utf8' codec can't decode byte 0x82 in position 31: invalid start byte

.tox/py27/lib/python2.7/encodings/utf_8.py:16: UnicodeDecodeError
```

After analyze the string `digest = '\x82|\xcb\x0e\xea\x8aplL4\xa1h\x91\xf8N{'`, I understand the reason why it raised the error. The `'\x82|\xcb\x0e\xea\x8aplL4\xa1h\x91\xf8N{'` is not `utf-8` encoded string, it's in `ISO 8859-1` encoding:

![2017-01-11 10 37 30](https://cloud.githubusercontent.com/assets/6299096/21829526/90af31c0-d7ea-11e6-91e5-365fc20945bb.png)


And Atom can verify that:

![2017-01-11 10 15 56](https://cloud.githubusercontent.com/assets/6299096/21828950/93a90e26-d7e7-11e6-91b4-ba4779e55e5d.png)

That is the reason why `utf-8` cannot decode `\x82`, which is indeed an invalid `utf-8` starting byte.

And I don't think `unicode-escape` encoding in the test case is correct, it should be `iso-8859-1`. The test case will pass if I change it this way:

```diff
     digest = '\x82|\xcb\x0e\xea\x8aplL4\xa1h\x91\xf8N{'
     sql = "select * from foo where bar = '{0}'".format(digest)
-    formatted = sqlparse.format(sql, reindent=True)
+    formatted = sqlparse.format(sql, reindent=True, encoding='iso-8859-1')
     tformatted = "select *\nfrom foo\nwhere bar = '{0}'".format(digest)
     if PY2:
-        tformatted = tformatted.decode('unicode-escape')

+        tformatted = tformatted.decode('iso-8859-1')
     assert formatted == tformatted
```

I think the default encoding should be `utf-8`, which is common way to solve encoding problem, and any other encoding should be specified, such as `encoding='iso-8859-1'` here. And in this case, a CLI option for encoding is necessary.

**Comment by twang2218** [comment]
I created a PR #316 to apply the above idea.
