### ISSUE TITLE
Unicode characters unsupported?

### ISSUE THREAD

**Issue by swillits** [andialbrecht/sqlparse#319]
When trying to format:

`select "tést" as pants`

> A Python error of type <type 'exceptions.UnicodeEncodeError'> occured:
'ascii' codec can't encode characters in position 9-10: ordinal not in range(128)

**Comment by vmuriart** [comment]
should be fixed on latest release from a few days ago

**Comment by andialbrecht** [comment]
I've just run this statement against 0.2.3 and it don't raises an error anymore.

**Comment by swillits** [comment]
Hmm. I'm still having the same exact issue with 0.2.3.

**Comment by vmuriart** [comment]
are you trying to run this from a python script? You may need to add an encoding header to your script

```python
# -*- coding: utf-8 -*-

import sqlparse
print("do stuff")
```

**Comment by swillits** [comment]
Actually, now I'm pretty sure this is my problem calling sqlparse through the Python C API. The string I'm passing in isn't being "decoded" properly. It works fine from the command line. Sorry for the noise.
