### ISSUE TITLE
Putting LIMIT on a new line

### ISSUE THREAD

**Issue by romainr** [andialbrecht/sqlparse#320]
Hi,

Not sure if you want it upstream, but we found it more friendly to have the LIMIT formatted to a newline. If you are interested, I could send a PR like:

https://review.cloudera.org/r/9466/

Before:
SELECT *
FROM `default`.`jobs`
GROUP BY loc
HAVING salary > 1 LIMIT 100;

-->

After:
SELECT *
FROM `default`.`jobs`
GROUP BY loc
HAVING salary > 1
LIMIT 100;

**Comment by andialbrecht** [comment]
This looks right. Please send a pull request!
