### ISSUE TITLE
Staircase formatting on INSERT with multiple values

### ISSUE THREAD

**Issue by andialbrecht** [andialbrecht/sqlparse#329]
Here's an example where formatting results in a staircase effect: 
```
>>> sql = """insert into foo values (1, 'foo'), (2, 'bar'), (3, 'baz');"""
>>> print(sqlparse.format(sql, reindent=True))
insert into foo
values (1,
        'foo'), (2,
                 'bar'), (3,
                          'baz');
```

**Comment by nihao** [comment]
I just altered the function `_process_parenthesis` of sqlparse.filters.reindent.

Get a right format result like below:
`
insert into foo
values
(1, 'foo'),
(2, 'bar'),
(3, 'baz');
`

but other statements with  wrong, like `case when`
`
SELECT from_unixtime
(stats_at, 'YYYY-MM-dd') AS stats_at,
       sum
(CASE isp WHEN 'union' THEN traffic END) AS china_union,
       sum
(CASE isp WHEN 'mobile' THEN traffic END) AS china_mobile,
       sum
(CASE isp WHEN 'telcom' THEN traffic END) AS china_telcom
FROM t_biz_traffic
GROUP BY stats_at
ORDER BY stats_at
`

**Comment by nihao** [comment]
Update `_process_parenthesis` function with code below, it solves my problems. please let me know if have a better method, thx.
```
    def _process_parenthesis(self, tlist):
        ttypes = T.Keyword.DML, T.Keyword.DDL
        _, is_dml_dll = tlist.token_next_by(t=ttypes)
        fidx, first = tlist.token_next_by(m=sql.Parenthesis.M_OPEN)

        print('the parenthesis is: ', tlist, 'type is', type(tlist.get_sublists().__next__()).__name__, 'sublist is', [type(t).__name__ for t in tlist.get_sublists()])
        with indent(self, 1 if is_dml_dll else 0):
            if isinstance(tlist.get_sublists().__next__(), sql.IdentifierList):
                tlist.tokens.insert(0, self.nl()) 
            else:
                with offset(self, self._get_offset(first) + 1):
                    self._process_default(tlist, not is_dml_dll)
```

**Comment by andialbrecht** [comment]
How does the result look like?

**Comment by nihao** [comment]
The statements after "values" does not wrap a new line,  but cause other problems.

need a new solution.
