### ISSUE TITLE
get table name failed when table name start with digits

### ISSUE THREAD

**Issue by fdbug** [andialbrecht/sqlparse#337]
i try to get table name like this:
`
sqlparse.parse("update table 1_data set a=1 where b=2")[0].get_name()
`
it return u'_data'

**Comment by vmuriart** [comment]
Which sql backend is this for?
AFAIK most backend's don't accept table names to start with a digit. The ANSI sql definition explicitly calls this out as well.

**Comment by fdbug** [comment]
the most pop database  # mysql!  :)
dont accept pure digit but with char or quote it with back ticks. 
like this   1_test,  `11`
https://dev.mysql.com/doc/refman/5.7/en/identifiers.html

**Comment by andialbrecht** [comment]
Bizarre ;) however, sqlparse should support this, especially since "_data"
as table name is just wrong.

fdbug <notifications@github.com> schrieb am Di., 23. Mai 2017, 04:18:
