### ISSUE TITLE
encode error

### ISSUE THREAD

**Issue by 554943871** [andialbrecht/sqlparse#338]
Traceback (most recent call last):
  File "/usr/local/bin/sqlformat", line 9, in <module>
    load_entry_point('sqlparse==0.2.4.dev0', 'console_scripts', 'sqlformat')()
  File "build/bdist.macosx-10.12-intel/egg/sqlparse/cli.py", line 177, in main
UnicodeEncodeError: 'ascii' codec can't encode characters in position 559-561: ordinal not in range(128)

version 0.2.4.dev0

**Comment by andialbrecht** [comment]
Could you provide the sql statement that produces this error? How did you
call the program?

554943871 <notifications@github.com> schrieb am Do., 25. Mai 2017, 04:42:

**Comment by 554943871** [comment]
SELECT a
FROM b
WHERE 1=1 and sex="男"
----------------------------
When formatting SQL with the Atom beautify plug-in, there are some Chinese characters in the SQL, and the files are UTF8 encoded

**Comment by andialbrecht** [comment]
hm... this seems to be a bug in Atom beautify plug-in.  Using the file in
[testfile.zip](https://github.com/andialbrecht/sqlparse/files/1028140/testfile.zip) with this statement and using the module itself everything works as expected.

```
>>> s = 'SELECT a FROM b WHERE 1=1 and sex="男"'
>>> print(sqlparse.format(s, reindent=True))
SELECT a
FROM b
WHERE 1=1
  and sex="男"
```

```
$ sqlformat --reindent test.sql 
SELECT a
FROM b
WHERE 1=1
  and sex="男"
```

**Comment by 554943871** [comment]
Oh,I see.
thank you very much!
