### ISSUE TITLE
ImportError: cannot import name engine

### ISSUE THREAD

**Issue by lovee20002002** [andialbrecht/sqlparse#341]
hi when i run 
import sqlparse 
get this error you can help me?
`ImportError                               Traceback (most recent call last)
<ipython-input-12-a7d2bcc8aacc> in <module>()
----> 1 import sqlparse

/home/reza/anaconda2/lib/python2.7/site-packages/sqlparse/__init__.py in <module>()
     11 
     12 # Setup namespace
---> 13 from sqlparse import engine
     14 from sqlparse import filters
     15 from sqlparse import formatter

ImportError: cannot import name engine`

**Comment by YannisPap** [comment]
Same here.

**Comment by lovee20002002** [comment]
Solved
i install by conda and get 0.1.9 version 
uninstall it then install by pip and solve my problam

**Comment by andialbrecht** [comment]
Doesn't have conda a custom package format? Maybe they're missing some
files?

lovee20002002 <notifications@github.com> schrieb am Di., 30. Mai 2017,
19:06:

**Comment by YannisPap** [comment]
> Solved
>i install by conda and get 0.1.9 version
>uninstall it then install by pip and solve my problam

This worked for me also.
