### ISSUE TITLE
sqlparse not formatting properly when sysdate is present

### ISSUE THREAD

**Issue by kasirajanss93** [andialbrecht/sqlparse#344]
Hi,

sqlparse is not formating properly when keyword sysdata is present in the SQL string.

**Comment by kasirajanss93** [comment]
SQL string input
"select sysdate, hello,t1,t2 from test"
-----------------------------------------
Format SQL output
SELECT sysdate, hello,
                t1,
                t2
FROM test

**Comment by andialbrecht** [comment]
Thanks for reporting!
