### ISSUE TITLE
Can't format file that contains the "�" character

### ISSUE THREAD

**Issue by odahcam** [andialbrecht/sqlparse#350]
I can't run the formatter in any file.

**`sqlparse` version:** 0.2.3 (should be the latest `pip` version, installed via `pip` yesterday)

**CLI:** cmder

**CLI output:**

```bash

C:\Users\xxx
λ sqlformat
usage: sqlformat  [OPTIONS] FILE, ...
sqlformat: error: too few arguments

C:\Users\xxx
λ cd Desktop\

C:\Users\xxx\Desktop
λ sqlformat ec2.sql
Traceback (most recent call last):
  File "c:\program files\easyphp-devserver-17\eds-binaries\python\python2711x86x170727210349\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\program files\easyphp-devserver-17\eds-binaries\python\python2711x86x170727210349\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Users\xxx\AppData\Roaming\Python\Scripts\sqlformat.exe\__main__.py", line 9, in <module>
  File "C:\Users\xxx\AppData\Roaming\Python\Python27\site-packages\sqlparse\cli.py", line 157, in main
    data = ''.join(open(args.filename, 'r', args.encoding).readlines())
  File "c:\program files\easyphp-devserver-17\eds-binaries\python\python2711x86x170727210349\lib\codecs.py", line 694, in readlines
    return self.reader.readlines(sizehint)
  File "c:\program files\easyphp-devserver-17\eds-binaries\python\python2711x86x170727210349\lib\codecs.py", line 603, in readlines
    data = self.read()
  File "c:\program files\easyphp-devserver-17\eds-binaries\python\python2711x86x170727210349\lib\codecs.py", line 492, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 347: invalid continuation byte
```

**Formatted file contents:**

```sql
-- Criar um programa que leia todos os registros da tabela employees. 
-- Caso o funcionário tenha trocado de cargo, acrescentar 15% ao salário, que será inserido no campo novo salario da tabela nova. 
-- Inserir também o nome (last_name) e o salário atual do funcionário.

SET SERVEROUTPUT ON;
    
DROP TABLE employees_salaryUpgrade;

CREATE TABLE employees_salaryUpgrade (
	"name" VARCHAR2(80) NOT NULL,
	"salary_old" FLOAT(4) NOT NULL,
	"salary_new" FLOAT(4)
);

DECLARE    
    V_any_rows_found NUMBER;
BEGIN

    FOR employee IN (SELECT employee_id, last_name, salary FROM employees)
    LOOP
    
        DBMS_OUTPUT.put(employee.employee_id);
        
        SELECT 
            COUNT(*) INTO V_any_rows_found
        FROM job_history 
        WHERE job_history.employee_id = employee.employee_id;
                
        IF V_any_rows_found IS NOT NULL AND V_any_rows_found > 0 THEN
            
            DBMS_OUTPUT.put_line(' - mudou de cargo!');
        
            INSERT INTO employees_salaryUpgrade VALUES (employee.last_name, employee.salary, employee.salary * 1.15);
        
        ELSE

            DBMS_OUTPUT.put_line(' - não mudou de cargo!');

        END IF;
    
    END LOOP;

END;

SELECT * FROM employees_salaryUpgrade;
```

**Comment by vmuriart** [comment]
A few questions to help on debugging

what version of sqlparse are you using?
whats the contents on the file that is failing? why do you think this is a win10 issue?

**Comment by odahcam** [comment]
I don't think it's an OS issue, I just don't have any idea of what it can be. 😆 
 
BTW I added some details to my first comment. 
I formatted my PC, so I installed everything yesterday, `python`, `pip`, etc.

**Comment by vmuriart** [comment]
No worries, the title of the issue seemed to indicate that it was a behavior you were seeing on Win10 only.

- Did it used to work before you formatted? 
- If you make a new file with the content below, does it work?

```
select 1 from dual
```

From looking at the contents you posted above, your file has special characters from Portuguese, which are most likely the ones that are causing the issue. The file itself is probably not `utf-8` encoded which is the default encoding we use (we don't try to guess the file encoding). You have two options for this:

- you can figure out what the encoding of the file is and pass that as a CLI argument `sqlformat --encoding=cp860 ec2.sql` (`cp860` is a guess, so you'll need to change that)
- you can re-encode the file to use utf-8. Most modern text editors will let you do this easily (sublime, atom, etc)

**Comment by odahcam** [comment]
I'll take a look soon.

* I never used this package before formatting.
* With a new file it did not worked.

The file i tryied to format unfortunaly isn't in UTF-8, it was written in Oracle's sqldeveloper.

**Comment by odahcam** [comment]
Well, after removing all the `�` characters, the formatter worked fine.

**Comment by andialbrecht** [comment]
When you try to format a file saved with a different encoding than utf-8, you can also try to use the --encoding command line flag for sqlformat to give the correct encoding on the command line. For example ```sqlformat --encoding=FOO my_file.sql```.
