### ISSUE TITLE
IndexError exception when parsing SQL statement with variables

### ISSUE THREAD

**Issue by Terseus** [andialbrecht/sqlparse#359]
I've found a curious issue with the following SQL statement:
`SELECT @min_price:=MIN(price), @max_price:=MAX(price) FROM shop;`

The functions `sqlparse.parse` throw an `IndexError` exception with it, but if I remove the final semicolon the statement is parsed correctly; `sqlparse.format` is also affected but only when `strip_comments=True` is used.

All these tests have been done in the 0.2.3 version and in the master branch, so the bug still exists.

I've tested the following situations (I removed the full stack trace for brevity):
* `sqlparse.parse` with semicolon:
```
In [2]: sqlparse.parse('SELECT @min_price:=MIN(price), @max_price:=MAX(price) FROM shop;')
...
~/programacion/python/sqlparse/sqlparse/sql.py in group_tokens(self, grp_cls, start, end, include_end, extend)
    285         """Replace tokens by an instance of *grp_cls*."""
    286         start_idx = start
--> 287         start = self.tokens[start_idx]
    288
    289         end_idx = end + include_end

IndexError: list index out of range
```
* `sqlparse.parse` without semicolon:
```
In [3]: sqlparse.parse('SELECT @min_price:=MIN(price), @max_price:=MAX(price) FROM shop')
Out[3]: (<Statement 'SELECT...' at 0x7F91945115E8>,)
```
* `sqlparse.format` with semicolon:
```
In [4]: sqlparse.format('SELECT @min_price:=MIN(price), @max_price:=MAX(price) FROM shop;')
Out[4]: 'SELECT @min_price:=MIN(price), @max_price:=MAX(price) FROM shop;'
```
* `sqlparse.parse` with semicolon and `strip_comments=True`:
```
In [5]: sqlparse.format('SELECT @min_price:=MIN(price), @max_price:=MAX(price) FROM test;', strip_comments=True)
...
~/programacion/python/sqlparse/sqlparse/sql.py in group_tokens(self, grp_cls, start, end, include_end, extend)
    285         """Replace tokens by an instance of *grp_cls*."""
    286         start_idx = start
--> 287         start = self.tokens[start_idx]
    288
    289         end_idx = end + include_end

IndexError: list index out of range
```
* `sqlparse.format` without semicolon and with `strip_comments=True`:
```
In [6]: sqlparse.format('SELECT @min_price:=MIN(price), @max_price:=MAX(price) FROM test', strip_comments=True)
Out[6]: 'SELECT @min_price:=MIN(price), @max_price:=MAX(price) FROM test'
```

**Comment by tsroten** [comment]
Also, see this issue: https://github.com/andialbrecht/sqlparse/issues/358

**Comment by andialbrecht** [comment]
Thanks a lot for reporting and especially for the great examples! I've
noticed this error a few times on sqlformat.org but was never able to find
a simple statement to reproduce it.

**Comment by Terseus** [comment]
Oops, looks like I duplicated your issue, sorry @tsroten, didn't saw it before.

**Comment by tsroten** [comment]
@Terseus No problem! 😄

**Comment by andialbrecht** [comment]
Thanks again for reporting and the good examples!

**Comment by andialbrecht** [comment]
BTW, I'm going to release a new version with this fix next week.

**Comment by tsroten** [comment]
@andialbrecht Thanks for the very quick fix!
