### ISSUE TITLE
Update Copyright header

### ISSUE THREAD

**Issue by vmuriart** [andialbrecht/sqlparse#372]
I was looking at the `SQLAlchemy` code and noticed the working on their header. Would you be open to using similar language for `sqlparse`?

```python
# Copyright (C) 2005-2017 the SQLAlchemy authors and contributors
# <see AUTHORS file>
```

On a separate note:
Looks like the year on the copyright notice should be the year of [first publication](http://www.contentious.com/2007/01/07/copyright-notice-is-the-year-really-necessary/).

**Comment by andialbrecht** [comment]
yepp, that looks reasonable
