### ISSUE TITLE
problem with renaming as "e1" or "e2" in from-clause

### ISSUE THREAD

**Issue by Meffi42** [andialbrecht/sqlparse#399]
I have a from-clause where I rename relations as "e1, e2, ..." - this seems problematic,
e.g., "e2" is recognized as a float:

>>> list( sqlparse.parse("select * from Eats e1, Eats e2")[0] )[6].value
'Eats'
>>> list( sqlparse.parse("select * from Eats e1, Eats e2")[0] )[8].value
'e1, Eats'

>>> list( sqlparse.parse("select * from Eats e1, Eats e2")[0] )[10].value
'e2'
>>> list( sqlparse.parse("select * from Eats e1, Eats e2")[0] )[10].ttype
Token.Literal.Number.Float

Using different identifiers, such as "a" or "b" works:

>>> list( sqlparse.parse("select * from Eats a, Eats b")[0] )[6].value
'Eats a, Eats b'

>>> type( list( sqlparse.parse("select * from Eats a, Eats b")[0] )[6] )
<class 'sqlparse.sql.IdentifierList'>

**Comment by collerek** [comment]
Can confirm this is still valid, is this related to exponentials, or it's a bug?
@andialbrecht, any thoughts?

**Comment by andialbrecht** [comment]
Yes, it's a bug. And it's fixed now. Thanks for reporting and bringing this up again!
