### ISSUE TITLE
List of supported SQL dialects

### ISSUE THREAD

**Issue by Tagar** [andialbrecht/sqlparse#402]
Trying to find a list of RDBMS/SQL backends/dialects that `sqlparse` targets to support?
Can't find it documented anywhere.
I see at least evidence of support for Oracle, MySQL, PosthreSQL, SQL Server
as I mentioned in https://github.com/apache/incubator-airflow/pull/2170#issuecomment-383472671 .

**Comment by andialbrecht** [comment]
sqlparse aims to be a generic SQL parser. There is no official list of
dialects. We've added some dialect specific features recently to improve
parsing. But there are no plans to have a dialect switch. Keep in mind that
sqlparse doesn't validate. sqlparse should also work in editing
environments where the sql statements are invalid most of the time.

2018-04-23 19:04 GMT+02:00 Ruslan Dautkhanov <notifications@github.com>:

**Comment by Tagar** [comment]
Thank you @andialbrecht !
