### ISSUE TITLE
sqlformat not being recognized but says it's installed

### ISSUE THREAD

**Issue by databasekevin** [andialbrecht/sqlparse#405]
Installed sqlparse from pip with the purpose of using with atom.beautify package (which isn't working). Tried testing out sqlformat with a test .sql file and no luck...

```
C:\Users\kkimm\AppData\Local\Programs\Python\Python36-32\Scripts>pip install --upgrade sqlparse
Requirement already up-to-date: sqlparse in c:\users\kkimm\appdata\local\program
s\python\python36-32\lib\site-packages (0.2.4)

C:\Users\kkimm\AppData\Local\Programs\Python\Python36-32\Scripts>python sqlformat test.sql --reindent
python: can't open file 'sqlformat': [Errno 2] No such file or directory
```
![image](https://user-images.githubusercontent.com/38899976/39838333-21419ec4-53a7-11e8-93ca-c8788fa90328.png)

**Comment by nickolay** [comment]
You probably have already figured it out, but the issue is that Windows Explorer doesn't show the true file name to you unless you enable it in its settings, it's "sqlformat.py".

**Comment by andialbrecht** [comment]
Not sure how it is invoked no Windows, but "python sqlformat test.sql" is wrong. It should be either "python -m sqlparse test.sql" (calling the installed module) or "sqlformat test.sql" if the script is callable that way on Windows.
