### ISSUE TITLE
Improve performance of reindent

### ISSUE THREAD

**Issue by andialbrecht** [andialbrecht/sqlparse#41]
*This is a **shadow issue** for [Issue 41 on Google Code](http://code.google.com/p/python-sqlparse/issues/detail?id=41) (from which this project was moved).
Added 2011-07-29T18:43:31.000Z by [albrecht.andi](http://code.google.com/u/albrecht.andi/).
Labels: Type-Defect, Priority-High.
Please make updates to the bug [there](http://code.google.com/p/python-sqlparse/issues/detail?id=41).*

# Original description

    Reindent filter has a lousy performance on certain statements. One of the &quot;statements of death&quot; is attached.
    
    The problem is that ReindentFilter._get_offset() is a performance hog. The number of calls to flatten() in offset calculation is totally insane. 
    
    Possible solutions are:
    - remember offsets
    - limit flatten() range
    - reimplement reindent using a different approach
    
    One problem is that the statement changes constantly in this phase of processing and I'm not sure if it makes sense to store some kind of state at all.
    
    NB, this causes DeadlineExceeded errors on App Engine

**Comment by JacekPliszka** [comment]
Got probably this issue as well, attached example code to code.google.com issue

**Comment by andialbrecht** [comment]
This should be resolved with 2bde1b9e494bc8673e0967a7b1f59150131659cc.
