### ISSUE TITLE
it got only id  column when run examples [column_defs_lowlevel.py]

### ISSUE THREAD

**Issue by geekmars** [andialbrecht/sqlparse#411]
i got id column only when i run column_defs_lowlevel.py, 
python version 3.4.1

**Comment by petergruenbeck** [comment]
It looks like the parser is incorrectly returning the 2nd and 3rd identifier as an <identifier list> paired with the attribute from the previous line. 

SQL = """CREATE TABLE foo (
             id integer primary key,
             title varchar(200) not null,
             description text);"""

>>> print(token_list.tokens[9])
key,
             title

>>> print(token_list.tokens[13])
not null,
             description

**Comment by petergruenbeck** [comment]
I've tracked the issue down to grouping.py function group_identifier_list which just looks for tokens separated by a ',', but does not check if the parameters are identifiers or not so its picking up <keyword><comma><identifier> rather than just looking for <identifier><comma><identifier>.
