### ISSUE TITLE
strip_comments causing syntax error

### ISSUE THREAD

**Issue by msardana94** [andialbrecht/sqlparse#425]
If there is no space between comments and keyword, the output causes a syntax error. Here's an example:

```python
import sqlparse

sql='''select * from table1--this is a comment
inner join table2 on table1.id = table2.id--this is a comment
where table1.a=1'''

sqlparse.format(sql,strip_comments=True)
```
This gives the following as output:
`select * from table1inner join table2 on table1.id = table2.idwhere table1.a=1`

**Comment by rafaelreuber** [comment]
+1

**Comment by rafaelreuber** [comment]
Any update on this? Would be really nice to have....
