### ISSUE TITLE
TokenList.get_alias() incorrect for IdentifierList

### ISSUE THREAD

**Issue by john-bodley** [andialbrecht/sqlparse#455]
The logic for detecting a [non-AS alias](https://github.com/andialbrecht/sqlparse/blob/d02339582f151d24bacefa636bc3955c2932c29f/sqlparse/sql.py#L348) seems to be incorrect, i.e., 
```
>>> from sqlparse import parse

>>> tlist = parse('x, y')[0][0]
>>> type(tlist)
<class 'sqlparse.sql.IdentifierList'>
>>> tlist.get_alias()
'y'
```
 
I was wondering whether the `IdentifierList` class should override the `get_alias` method to return `None`.

**Comment by john-bodley** [comment]
Note this also seems to be an issue for `Comparison` and `Operation`, e.g:
```
>>> tlist = parse('x > y')[0][0]   
>>> type(tlist)
<class 'sqlparse.sql.Comparison'>
>>> tlist.get_alias()
'y'
```
and
```
>>> tlist = parse('x / y')[0][0]
>>> type(tlist)
<class 'sqlparse.sql.Operation'>
>>> tlist.get_alias()
'y'
```

**Comment by andialbrecht** [comment]
@john-bodley thanks for the pull request! That was a great pointer in the right direction and I adopted some parts of you pull request, but solved it slightly different. 

Thanks!
