### ISSUE TITLE
Support double slash (//) comments

### ISSUE THREAD

**Issue by theianrobertson** [andialbrecht/sqlparse#456]
Not sure how wide-spread this is, and not sure how much you'd like to support non-standard functionality, but some SQL flavours support double-slashes (`//`) in addition to double-dashes (`--`) for single-line comments, like:

```sql
SELECT
    some_field, // first comment
    some_other_field -- second comment
FROM
    table
```

At least [Snowflake](https://support.snowflake.net/s/article/how-to-comment-or-uncomment-multiple-lines-in-the-sql-worksheet) and MS [U-SQL](https://docs.microsoft.com/en-us/u-sql/language-elements/double-slash-comment) use the double-slash.  (though GitHub syntax highlighting doesn't 😁).  May be something that could be an optional flag?

**Comment by andialbrecht** [comment]
I skimmed through the PostgreSQL, MySQL and Oracle docs and it seems that double-slash isn't used anywhere. I think it's safe to merge this change even without a flag.
