### ISSUE TITLE
Should other format codes be supported for paramstyle?

### ISSUE THREAD

**Issue by dmalan** [andialbrecht/sqlparse#470]
Per [PEP 249](https://www.python.org/dev/peps/pep-0249/#paramstyle) (and https://github.com/andialbrecht/sqlparse/issues/103), there are five prescribed values for `paramstyle`, among them `format` (e.g., `%s`) and `pyformat` (e.g., `%(name)s`). Is the general consensus in the Python community that only `s` should be supported for those two? Or should, e.g., `%d`, `%(id)d`, et al. be supported, as might be implied by "ANSI C printf format codes" and "Python extended format codes", both plural?

For our own library, [https://github.com/cs50/python-cs50](python-cs50), we too have adopted the narrower definition for the moment because we're using [sqlparse](https://github.com/andialbrecht/sqlparse) as a dependency but wonder if sqlparse's [regexes](https://github.com/andialbrecht/sqlparse/blob/master/sqlparse/keywords.py#L42-L44) should perhaps recognize other codes?

Some Googling led us to [pymssql](http://pymssql.org/en/stable/migrate_1_x_to_2_x.html?highlight=pyformat#parameter-substitution), which notes that "is not clear from PEP 249 whether other types should be supported" and that "the general consensus is that the string format should be the only one required," per [this mailing list thread](http://python.6.x6.nabble.com/Some-obscurity-with-paramstyle-td2163302.html). Not sure if there's a more authoritative answer out there?

**Comment by andialbrecht** [comment]
Thanks for pointing to pymssql. I use psycopg2 (for PostgreSQL) most of the time and their documentation is pretty clear on this topic:

> The variables placeholder must always be a %s, even if a different placeholder (such as a %d for integers or %f for floats) may look more appropriate
http://initd.org/psycopg/docs/usage.html#passing-parameters-to-sql-queries

I tend to close this issue unless a different usecase comes up somewhere. See also my previous comment on #471, I'm fine with adding more options for placeholders when there's a (documented) need to it.
