### ISSUE TITLE
Should placeholders be allowed to start with dollar signs?

### ISSUE THREAD

**Issue by dmalan** [andialbrecht/sqlparse#471]
Per https://github.com/andialbrecht/sqlparse/blob/master/sqlparse/keywords.py#L42-L44, below, it seems that a `tokens.Name.Placeholder` is allowed to start with `$` (and, it would seem, `?`) even though [PEP 249](https://www.python.org/dev/peps/pep-0249/#paramstyle) only prescribes placeholders starting with `:` (or of the form `%s` or `%(name)s`)? 

```python
(r'\?', tokens.Name.Placeholder),
(r'%(\(\w+\))?s', tokens.Name.Placeholder),
(r'(?<!\w)[$:?]\w+', tokens.Name.Placeholder),
```

Indeed, a query like

```sql
SELECT * FROM foo WHERE bar = $bar
```

yields

```
[..., <Placeholder '$foo' at 0x7FE446185948>]
```

I gather that dollar signs might relate to support for Oracle (cf. https://github.com/andialbrecht/sqlparse/commit/358ad4b9754721f69c6b40333653bd84edb8634f), but should, "placeholders," in fact, be allowed to start with anything other than `:`, `?`, and `\w`?

**Comment by andialbrecht** [comment]
sqlparse doesn't assume that it's only used within a Python context. So other placeholders than the ones described in PEP 249 should be parsed too. Placeholders starting with dollar signs are used by node-postgres, for example.

BTW, the commit you've mentioned was just a bug fix where sqlparse didn't recognized a table name containing a dollar sign as a table name (which is allowed in Oracle).
