### ISSUE TITLE
Strip multiple whitespace within parentheses

### ISSUE THREAD

**Issue by john-bodley** [andialbrecht/sqlparse#473]
I was wondering whether the [StripWhitespaceFilter. _stripws_parenthesis](
https://github.com/andialbrecht/sqlparse/blob/3853a076c63493f43e969cf4ddd2e642e92f02fb/sqlparse/filters/others.py#L71) method should be updated to strip multiple occurrences of whitespaces within parentheses, i.e., 
```
def _stripws_parenthesis(self, tlist):
    while tlist.tokens[1].is_whitespace:
        tlist.tokens.pop(1)
    while tlist.tokens[-2].is_whitespace:
        tlist.tokens.pop(-2)
    self._stripws_default(tlist)
```
rather than just the first occurrence.

**Comment by andialbrecht** [comment]
Agreed. This looks much cleaner to me.
