### ISSUE TITLE
Version 0.3.0 breaks parsing when there is a url

### ISSUE THREAD

**Issue by nolamesa** [andialbrecht/sqlparse#476]
It appears that the new version breaks statement parsing when there is a url. Here's an easy way to reproduce:

```python
sqlparse.parse("add file http://abc.com; select 1;")
```
In v0.3.0 this returns one statement instead of 2 unless you remove the `http://` in which case it works as expected.

EDIT it appears to be introduced here https://github.com/andialbrecht/sqlparse/commit/170010e7d709f2145169d23482d006dc56856256

**Comment by tobymao** [comment]
as // isn't valid in most dialects, we should make this an opt in flag or remove it

**Comment by tobymao** [comment]
https://github.com/andialbrecht/sqlparse/pull/477

**Comment by andialbrecht** [comment]
@nolamesa, I'm not sure how valid this use case is: Parsing fails on the part of your string which isn't SQL at all and you'd have the same problem if the URL contains a double-dash, for example http://example.com/foo--bar.html

@tobymao maybe reverting the change is a very drastic option. But I'm considering to add a "dialact" flag to the parser. There are some more cases, where such a flag would be useful to fine-tune the parser for certain dialects.

**Comment by nolamesa** [comment]
@andialbrecht it's a very common case in dialects like hive where you need to import a jar for your functions. Your counter example is fair but probably more of an edge case compared to the // which is required as part of the url

**Comment by andialbrecht** [comment]
@nolamesa Thanks for the feedback. This really helps me to understand how a possible "dialect flag" could work! 

You're right. My example is somewhat constructed compared to the // which is part of the protocol. I'm not familiar with hive (neither with U-SQL or Snowflake which use the // for comments): You've said it's very common to use such import in hive, is this parsing conflict a real show stopper for you? If so, I'd consider to accept the pull request by @tobymao that reverts the change until we've found a better solution to make the parse more dialect-aware.

**Comment by nolamesa** [comment]
We currently solved this on our side by detecting the url and adding a new line after it since we dont care about the correct parsing of that specific statement but all the rest. I am assuming though other people might fall into this bug

**Comment by andialbrecht** [comment]
ok, I'm aware if this issue. Let me know, if you're aware that it bubbles
up somewhere else.

Am Do., 14. März 2019 um 20:50 Uhr schrieb Nikos Diamantopoulos <
notifications@github.com>:

**Comment by andialbrecht** [comment]
ok, so I've merged the pull request then ;)

Thank you both for the input on this topic!
