### ISSUE TITLE
NULLS is parsed as an identifier

### ISSUE THREAD

**Issue by rsussland** [andialbrecht/sqlparse#487]
NULLS is parsed as an identifier. This caused a bug for me. I'm not an SQL expert, but it seems that it should be a keyword similar to NULL, NOT NULL, OR LAST. Otherwise everyone looking for a table name or field name is going to run into this when they filter on identifiers.

E.g.:
>>> stmt = sqlparse.parse("SELECT A FROM B WHERE X=NULL AND Y NOT NULL ORDER BY C NULLS LAST")[0]
>>> stmt._pprint_tree()
|- 0 DML 'SELECT'
|- 1 Whitespace ' '
|- 2 Identifier 'A'
|  `- 0 Name 'A'
|- 3 Whitespace ' '
|- 4 Keyword 'FROM'
|- 5 Whitespace ' '
|- 6 Identifier 'B'
|  `- 0 Name 'B'
|- 7 Whitespace ' '
|- 8 Where 'WHERE ...'
|  |- 0 Keyword 'WHERE'
|  |- 1 Whitespace ' '
|  |- 2 Comparison 'X=NULL'
|  |  |- 0 Identifier 'X'
|  |  |  `- 0 Name 'X'
|  |  |- 1 Comparison '='
|  |  `- 2 Keyword 'NULL'
|  |- 3 Whitespace ' '
|  |- 4 Keyword 'AND'
|  |- 5 Whitespace ' '
|  |- 6 Identifier 'Y'
|  |  `- 0 Name 'Y'
|  |- 7 Whitespace ' '
|  |- 8 Keyword 'NOT NU...'
|  `- 9 Whitespace ' '
|- 9 Keyword 'ORDER ...'
|- 10 Whitespace ' '
|- 11 Identifier 'C NULLS'
|  |- 0 Name 'C'
|  |- 1 Whitespace ' '
|  `- 2 Identifier 'NULLS'
|     `- 0 Name 'NULLS'
|- 12 Whitespace ' '
`- 13 Keyword 'LAST'

**Comment by andialbrecht** [comment]
Thanks for reporting!

**Comment by rsussland** [comment]
Wow, that was fast! Thanks for building this awesome tool.
