### ISSUE TITLE
Adding timezone info to identifier in SELECT clause causes alias to be ignored

### ISSUE THREAD

**Issue by KSauri** [andialbrecht/sqlparse#489]
I was unable to find this issue so posting it.

The parser ignores aliases when timezone information is added.  I am using postgresql.

This should be enough to replicate:
```python
import sqlparse

query = "SELECT publish_at AT TIME ZONE 'UTC' AS first_publish_date FROM stories;"
parsed = sqlparse.parse(query)
publish_at_identifier = parsed[0].tokens[2]

assert publish_at_identifier.has_alias() == False 
```

If you inspect the tokens, `UTC` is being assigned the alias. Eg:
```python
# ... previous code
parsed[0].tokens[10].has_alias() == True # UTC
```

I'd be happy to look into this issue and come up with a PR.

**Comment by andialbrecht** [comment]
This should be fixed now. Thanks for reporting!

**Comment by KSauri** [comment]
Thanks super useful!
