### ISSUE TITLE
Error splitting oracle create index and alter  index statement

### ISSUE THREAD

**Issue by calvinkyte** [andialbrecht/sqlparse#491]
In [10]: sqlparse.split('create index tom.i$bs_460$RID on tom.bs_460(RID) local parallel 8;alter index tom.i$bs_460$RID noparallel;')                                       
Out[10]: ['create index tom.i$bs_460$RID on tom.bs_460(RID) local parallel 8;alter index tom.i$bs_460$RID noparallel;']

**Comment by andialbrecht** [comment]
Thanks for reporting!
