### ISSUE TITLE
Naming inconsistencies: sqlparse vs sqlformat vs python-sqlparse

### ISSUE THREAD

**Issue by MartinThoma** [andialbrecht/sqlparse#504]
I just installed sqlparse and was wondering why the CLI command "sqlparse" did not work. I think the CLI command "sqlparse" should be added. Why is it called different in the first place?

And why does the documentation call it "python-sqlparse"?

**Comment by andialbrecht** [comment]
It's called "sqlformat" because the command line script does nothing else than providing the formatting functions of sqlparse.
