### ISSUE TITLE
Broken Example - column_defs_lowlevel.py - "TypeError: unsupported format string passed to Identifier.__format__" , name/definition not working correctly.

### ISSUE THREAD

**Issue by plasx** [andialbrecht/sqlparse#526]
# column_defs_lowlevel.py TypeError / Misplaced values in output

### Output:
Upon running the example  [column_defs_lowlevel.py](https://github.com/andialbrecht/sqlparse/blob/master/examples/column_defs_lowlevel.py#L48)
with python 3.7.6, the script throws a TypeError:

    osxuser$ python --version
    Python 3.7.6
    osxuser$ python column_defs_lowlevel.py
    Traceback (most recent call last):
      File "column_defs_lowlevel.py", line 50, in <module>
        name=column[0], definition=''.join(str(t) for t in column[1:])))
    TypeError: unsupported format string passed to Identifier.__format__

### Output with string conversion

Upon converting `column[0]` to `str(column[0])` on [line 50](https://github.com/andialbrecht/sqlparse/blob/master/examples/column_defs_lowlevel.py#L50) the error goes away but only the first column is printed under `NAME` which is id, the rest of the columns and information seem to be combined into `DEFINITION` as shown below. 

    osxuser$ python column_defs_lowlevel.py
    NAME: id         DEFINITION:  integer primary key,
                 title varchar(200) not null,
                 description text

### How Output should appear
from my understanding, each column should be printed under name and column type under definition which would appear as:

    osxuser$ python column_defs_lowlevel.py
    NAME: id                   DEFINITION: integer primary key
    NAME: title                DEFINITION: varchar(200) not null
    NAME: description          DEFINITION: text

**Comment by andialbrecht** [comment]
Thanks for reporting! I've just refactored the code of column_defs_lowlevel.py so that it works again. However, keep in mind, that all that low-level stuff isn't documented and may change at any time.
