### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by aarondav** [andialbrecht/sqlparse#533]
We were hoping to use the latest version of sqlparse in [MLflow](https://github.com/mlflow/mlflow) to simplify parsing of LIKE/ILIKE queries in the MLflow search syntax, based on this PR: https://github.com/andialbrecht/sqlparse/pull/525 (corresponding MLflow PR [here](https://github.com/mlflow/mlflow/pull/2217)).

The last release seems to be from March 2019 -- would it be possible to get a new release with the latest changes, and what kind of timeline might we expect (to know if we should implement a workaround temporarily)?

**Comment by andialbrecht** [comment]
I'm still hunting an issue that occasionally pops up in my environment. But expect a new release at the end of this month, either with or without a fix for that rare bug I'm seeing.

**Comment by dbczumar** [comment]
Hi @andialbrecht, just pinging on this! It would be great to have a new release of `sqlparse` to facilitate MLflow feature development (I'm sure folks will appreciate all of the other new `sqlparse` features as well).

**Comment by andialbrecht** [comment]
Yepp, tomorrow is the day ;)

**Comment by andialbrecht** [comment]
There it is: https://pypi.org/project/sqlparse/0.3.1/
