### ISSUE TITLE
Statement.get_name() returns None for a complete query

### ISSUE THREAD

**Issue by pasenor** [andialbrecht/sqlparse#536]
The following used to print 'foo', but does not any more after the upgrade to 0.3.1:

    >>> import sqlparse
    >>> query = "drop table foo;"
    >>> sqlparse.parse(query)[0].get_name()
    None

**Comment by andialbrecht** [comment]
yeah, but that is the correct behavior. `sqlparse.parse(query)[0]` returns the Statement itself as an instance and `get_name()` should return `None` for this object. You can access the name of the table by using `sqlparse.parse(query)[0].tokens[4].get_name()`. This works in both versions.
