### ISSUE TITLE
Add config files for pre/post Github hooks?

### ISSUE THREAD

**Issue by armaandhull** [andialbrecht/sqlparse#537]
Can we add a yaml and config file for this repo to be used for git hooks e.g pre-commit?

**Comment by andialbrecht** [comment]
Why?

Armaan Dhull <notifications@github.com> schrieb am Fr., 6. März 2020, 17:50:

**Comment by armaandhull** [comment]
@andialbrecht because it helps `sqlformat` work as a pre-commit hook with [pre-commit](https://pre-commit.com/)

**Comment by armaandhull** [comment]
something like 
```
-  id: sqlformat
   name: sqlformat
   stages: [commit]
   language: system
   entry: sqlformat
   types: [sql]
```

**Comment by andialbrecht** [comment]
ah, ok. But shouldn't the hooks be added in the repository where you want
to use it, and not in the sqlparse repo itself?

Armaan Dhull <notifications@github.com> schrieb am Fr., 6. März 2020, 18:55:

**Comment by armaandhull** [comment]
@andialbrecht afaik the hook definition/settings i.e. `.pre-commit-hooks.yaml` need to be in the repo _being used by pre-commit_ and the repo using the hook needs to have a `.pre-commit-config.yaml`

**Comment by andialbrecht** [comment]
Pretty sure you're referring to https://pre-commit.com/ and that those configurations need to be added to the .pre-commti-hooks.yaml file in your repository. But not in the repository of the tools you want to use in a hook.

**Comment by armaandhull** [comment]
@andialbrecht take a look at https://github.com/psf/black/blob/master/.pre-commit-hooks.yaml and https://github.com/timothycrosley/isort/blob/develop/.pre-commit-hooks.yaml. These hooks yaml files are what allow users to use them with pre-commit.

Also, https://pre-commit.com/#creating-new-hooks

>A git repo containing pre-commit plugins must contain a .pre-commit-hooks.yaml file that tells pre-commit:

**Comment by PeterFogh** [comment]
@armaandhull is correct. The sqlparse repo needs a `.pre-commit-hooks.yaml` file to enable use of the `sqlformat` CLI in pre-commit hooks. Why was this issue closed? Was it decided that sqlparse should not support pre-commit? :)

**Comment by ashrub-holvi** [comment]
> I'm not so much a fan of pre-commit hooks myself

but why? IMO really useful tool

> feel free to test it out and give feedback

It works! I am not yet fully happy with formatting details (e.g. formatting of "ALTER TABLE"), but it's separate topic and of course formatting it's not a main thing for parsing library, so, anyway, many thanks!
