### ISSUE TITLE
Represent parsed object as json

### ISSUE THREAD

**Issue by MuriloSchaefer** [andialbrecht/sqlparse#561]
Hello everyone!

I just found this awesome library and I'm using it to enforce policies on queries. To do so, I need to parse the sql, then apply all policies on it, and finally compose the sql back again. The policy engine will be made by an external service, and I'm going to access it via an API endpoint.

This endpoint expect an sql parsed object as json ( can be organized in any json structure ). So I want to know if there is a way to represent the parsed object as a json object. 

I'm willing to code it if needed, just need some guidance of how to do it (I promise I create a PR if you get interested in it)

**Comment by andialbrecht** [comment]
Hi @MuriloSchaefer ,

have a look at the `_pprint_tree` function: https://github.com/andialbrecht/sqlparse/blob/master/sqlparse/sql.py#L180
It does something similar. It prints out the parsed tree. I don't see much use for such a JSON format in sqlparse itself since the needs for the resulting JSON might differ for every user. 

Here's a little example, that should point you in the right direction:
```
>>> import sqlparse
>>> parsed = sqlparse.parse('select * from foo where val1 = 123 and val2 = 456;')[0]
# if you just want a flat list, it's simple as
>>> list((t._get_repr_name(), t.value) for t in parsed.flatten())
[('DML', 'select'),
 ('Whitespace', ' '),
 ('Wildcard', '*'),
 ('Whitespace', ' '),
 ('Keyword', 'from'),
 ('Whitespace', ' '),
 ('Name', 'foo'),
 ('Whitespace', ' '),
 ('Keyword', 'where'),
 ('Whitespace', ' '),
 ('Name', 'val1'),
 ('Whitespace', ' '),
 ('Comparison', '='),
 ('Whitespace', ' '),
 ('Integer', '123'),
 ('Whitespace', ' '),
 ('Keyword', 'and'),
 ('Whitespace', ' '),
 ('Name', 'val2'),
 ('Whitespace', ' '),
 ('Comparison', '='),
 ('Whitespace', ' '),
 ('Integer', '456'),
 ('Punctuation', ';')]
# if you want it nested you'll need a little helper to be called recusively:
>>> def yield_children(token):
...     for t in token.tokens:
...         if t.is_group:
...             yield list(yield_children(t))
...         else:
...             yield (t._get_repr_name(), t.value)
...
>>> list(yield_children(parsed))
[('DML', 'select'),
 ('Whitespace', ' '),
 ('Wildcard', '*'),
 ('Whitespace', ' '),
 ('Keyword', 'from'),
 ('Whitespace', ' '),
 [('Name', 'foo')],
 ('Whitespace', ' '),
 [('Keyword', 'where'),
  ('Whitespace', ' '),
  [[('Name', 'val1')],
   ('Whitespace', ' '),
   ('Comparison', '='),
   ('Whitespace', ' '),
   ('Integer', '123')],
  ('Whitespace', ' '),
  ('Keyword', 'and'),
  ('Whitespace', ' '),
  [[('Name', 'val2')],
   ('Whitespace', ' '),
   ('Comparison', '='),
   ('Whitespace', ' '),
   ('Integer', '456')],
  ('Punctuation', ';')]]
```
