### ISSUE TITLE
Incorrect split results

### ISSUE THREAD

**Issue by jamie-burks** [andialbrecht/sqlparse#580]
**What were you trying to accomplish?**
Using `sqlparse.split` to split these SQL commands loaded from a text file. SQL syntax is correct and accepted by MySQL.

```
drop procedure if exists podLogAggregator;

create procedure podLogAggregator()
begin
  declare exit handler for sqlexception
  begin
    rollback;
  end;
  
  start transaction;

  set @maxPodLogId = (select max(podLogId) from podLogs);

  insert into riderDailyStats (userId, statDate, rideSeconds, pumpSeconds, earnings, latestDatetime)
  select pl.userId, date(pl.startedAt),
    sum(case when durationType = 'pumpTime' then duration else 0 end),
    sum(case when durationType = 'ridetime' then duration else 0 end),
    max(date(startedAt))
  from podLogs pl
  join users u
  on u.adId = pl.userId
  where pl.podLogId > (
    select coalesce(lastPodLogIdProcessed, 0)
    from podLogSummaryControl where podLogSummaryControlId = 1
    )
  and pl.podLogId <= @maxPodLogId
  and pl.durationType in ('pumpTime','rideTime')
  group by pl.userId, date(pl.startedAt)
  on duplicate key update
    rideSeconds = rideSeconds + values(rideSeconds),
    pumpSeconds = pumpSeconds + values(pumpSeconds),
    latestTimestamp = if(values(latestTimestamp) > latestTimestamp, values(latestTimestamp), latestTimestamp);

  commit;
end;
```

## Expected Behavior
`sqlparse.split` should split this text into 2 statements - `drop procedure` and `create procedure`.

## Current Behavior
`sqlparse.split` is incorrectly splitting the `create procedure` statement after the `insert into` statement's last line `latestTimestamp = if(values(...`

## Steps to Reproduce (for bugs)
Use the above script text as input to sqlparse.split

## Environment
- Python 3.8
- sqlparse 0.3.1

**Comment by jamie-burks** [comment]
Here is a minimal test case that narrows the problem down to the presence of the `sum(case...` statement vs. a simple column select. I also tried adding an alias to the `sum(case...` statement but that did not change the behavior. Interestingly though changing the statement to `sum(if(column = 'value', column, 0))` does work around the problem.

```
import sqlparse

sql1 = '''create procedure procName()
begin
  insert into tableA (column)
  select sum(case when column = 'value' then column else 0 end)
    from tableB
  on duplicate key update column = column + (column);
end;'''

sql2 = '''create procedure procName()
begin
  insert into tableA (column)
  select column
    from tableB
  on duplicate key update column = column + (column);
end;'''

print(len(sqlparse.split(sql1)))
print(len(sqlparse.split(sql2)))
```

**Comment by charettes** [comment]
These things often go unnoticed, but just wanted to drop a thank you for reporting this issue @jamie-burks, maintaining this package, and resolving this particular issue @andialbrecht.

We were running into this particular problem and it's always a good feeling when you stumble upon a problem to see that someone took the time to report it and that it's already resolved in a version you can simply update to.

**Comment by andialbrecht** [comment]
It seems, that this problem came up as a regression, see #784
