### ISSUE TITLE
Bug: get_real_name() do not return a full name of an identifier

### ISSUE THREAD

**Issue by evyasonov** [andialbrecht/sqlparse#585]
Hello

`get_real_name()` do not return a full name of an identifier.

Here is my identifier:
```
cardinality(array_distinct(flatten(array_agg(column)))) AS alias
```

When I call `.get_real_name()`, I get just 
```
'cardinality'
```
,  but I expect
```
'cardinality(array_distinct(flatten(array_agg(column))))'
```

Can you please fix it

Thanks in advance

**Comment by andialbrecht** [comment]
Hi, this is the intended behavior. `get_real_name()` returns the name, here the name of the function. To achieve what you try to achieve you can go one step deeper and inspect the tokens in the parsed statement. For example
```
>>> parsed = sqlparse.parse('cardinality(array_distinct(flatten(array_agg(column)))) AS alias')[0]
>>> identifier = parsed.tokens[0]
>>> print(identifier)
cardinality(array_distinct(flatten(array_agg(column)))) AS alias
>>> function = identifier.tokens[0]
>>> print(function)
cardinality(array_distinct(flatten(array_agg(column))))
>>>
```

**Comment by evyasonov** [comment]
@andialbrecht 
Got it! Thank you very much for the helpful answer!
