### ISSUE TITLE
print statement in ReindentFilter outputs where token info to stdout 

### ISSUE THREAD

**Issue by lukewarm** [andialbrecht/sqlparse#586]
I just want to report that [this commit](https://github.com/andialbrecht/sqlparse/commit/11a6b7db8b19bf1f92754a6272839c66ee630683) added a [print statement](https://github.com/andialbrecht/sqlparse/blob/d14d75e2f12c1932e1032460337831efb33f83ee/sqlparse/filters/reindent.py#L108) and it adds output that the end users don't necessarily care. 

I'm not sure if this is intentional. The code is included in the latest release on Pypi.

Thanks.

**Comment by andialbrecht** [comment]
Thanks for reporting!! 🙈
