### ISSUE TITLE
python setup.py install not working for sqlparse - SSL cert error

### ISSUE THREAD

**Issue by andyguwc** [andialbrecht/sqlparse#587]
if I have `install_requires=['sqlparse==0.3.1']` in my setup.py and run python setup.py install it errors out. Same issue for other versions too.

Reading https://pypi.python.org/simple/sqlparse/
Download error on https://pypi.python.org/simple/sqlparse/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777) -- Some packages may not be found!
Couldn't find index page for 'sqlparse' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777) -- Some packages may not be found!
No local packages or working download links found for sqlparse==0.3.1

**Comment by andialbrecht** [comment]
This has nothing to do with sqlparse, but with PyPI itself.
