### ISSUE TITLE
sqlparse.split can't split sqls correctly in one case

### ISSUE THREAD

**Issue by Shawn001** [andialbrecht/sqlparse#588]
for example:

sqls2="grant insert,update,delete on test.test1 to lili@`192.168.11.23`; grant update,insert,select on test1.test2 to lili2@`10.10.11.12`;"
for st in sp.split(sqls2):
...     print(st)
... 
grant insert,update,delete on test.test1 to lili@`192.168.11.23`; grant update,insert,select on test1.test2 to lili2@`10.10.11.12`;     ---------**in one line still**

sqls2="grant insert,update,delete on test.test1 to lili@`192.%`; grant update,insert,select on test1.test2 to lili2@`10.10.11.12`;" 
for st in sp.split(sqls2):
...     print(st)
... 
grant insert,update,delete on test.test1 to lili@`192.%`;
grant update,insert,select on test1.test2 to lili2@`10.10.11.12`;    ----**have been splited into. two lines**

the differnence between two sqls is :

first sqls2 : lili@`192.168.11.23`
second sqls2: lili@`192.%`

sqlparse version is:

 print(sp.__version__)
0.4.1

**Comment by andialbrecht** [comment]
hm... I can't reproduce this issue:
```
>>> import sqlparse
>>> sqls2="grant insert,update,delete on test.test1 to lili@192.168.11.23; grant update,insert,select on test1.test2 to lili2@10.10.11.12;"
>>> for st in sqlparse.split(sqls2):
...     print(st)
...
grant insert,update,delete on test.test1 to lili@192.168.11.23;
grant update,insert,select on test1.test2 to lili2@10.10.11.12;
>>> print(len(sqlparse.split(sqls2)))
2
>>>
```

**Comment by Shawn001** [comment]
it doesn't work with  ` backtick quotes.

>>> import sqlparse
>>> sqls2="grant insert,update,delete on test.test1 to lili@`192.168.11.23`; grant update,insert,select on test1.test2 to lili2@10.10.11.12;"
>>> for st in sqlparse.split(sqls2):
...     print(st)
...
grant insert,update,delete on test.test1 to lili@`192.168.11.23`;; grant update,insert,select on test1.test2 to lili2@`10.10.11.12`;
>>> print(len(sqlparse.split(sqls2)))
1
>>>

**Comment by andialbrecht** [comment]
ah! Thanks! They were eaten up by githubs markdown machinery 😋

**Comment by andialbrecht** [comment]
hm... but still not reproducable by me 🤔 
```
>>> import sqlparse
>>> sqls2="grant insert,update,delete on test.test1 to lili@`192.168.11.23`; grant update,insert,select on test1.test2 to lili2@10.10.11.12;"
>>> for st in sqlparse.split(sqls2):
...     print(st)
...
grant insert,update,delete on test.test1 to lili@`192.168.11.23`;
grant update,insert,select on test1.test2 to lili2@10.10.11.12;
>>> print(len(sqls2))
129
>>> print(len(sqlparse.split(sqls2)))
2
```

**Comment by Shawn001** [comment]
Thanks.... I've tested with sqlparse-0.4.2.dev0, it worked.


Installed /usr/local/lib/python3.8/site-packages/sqlparse-0.4.2.dev0-py3.8.egg
Processing dependencies for sqlparse==0.4.2.dev0
Finished processing dependencies for sqlparse==0.4.2.dev0

**Comment by andialbrecht** [comment]
Thanks! I can reproduce it with the statement above. Here's a little bit more simplified example:
```
>>> sqlparse.split("grant foo to user1@`myhost`; grant bar to user1@`myhost`;")
['grant foo to user1@`myhost`; grant bar to user1@`myhost`;']
```
