### ISSUE TITLE
grouping need to stop using .remove()

### ISSUE THREAD

**Issue by bittrance** [andialbrecht/sqlparse#62]
Doing tlist.tokens.remove() is expensive on large lists. A typical "max size" MySQL INSERT statement (about 1 MByte in size) 79 out of 124 seconds are spent doing .remove().

**Comment by andialbrecht** [comment]
Pretty sure that this is related to other performance bugs that should be resolved with 2bde1b9e494bc8673e0967a7b1f59150131659cc

**Comment by vmuriart** [comment]
@minexew @bittrance , just updated to code replace `tokens.remove()` from the parsing/grouping portion of the code. Instead I place a list comprehension which [*should* help improve](http://stackoverflow.com/questions/5745881/fast-way-to-remove-a-few-items-from-a-list-queue) the performance.
If you are still seeing performance issues, feel free to open a new ticket. Thanks!
