### ISSUE TITLE
sqlparse.utils.remove_quotes does not remove backtick

### ISSUE THREAD

**Issue by codenamelxl** [andialbrecht/sqlparse#628]
Should back tick `` ` `` considered to be a quote character ?

For example `` `test_schema` `` when passed to remove_quotes() should return schema name without the backtick. 
[https://github.com/andialbrecht/sqlparse/blob/23d29933ddc4272b495d36e0e32d3eaf0c3ef76d/sqlparse/utils.py#L58](https://github.com/andialbrecht/sqlparse/blob/23d29933ddc4272b495d36e0e32d3eaf0c3ef76d/sqlparse/utils.py#L58)

I'm not too sure if adding backtick to this line will break anything. If it's OK to do, I'll send a PR.

**Comment by shiyishiaa** [comment]
I wonder if there is a method or argument to remove all the backticks or quotes?
