### ISSUE TITLE
can sqlparse.split( split by other characters but semicolon?

### ISSUE THREAD

**Issue by yx91490** [andialbrecht/sqlparse#657]

**Comment by andialbrecht** [comment]
Which ones and why?

**Comment by yx91490** [comment]
> Which ones and why?

sqlparse.split(sql) this one, I want to support '\G' as separator in impala-shell formerly, I can't implement it in a directly way because sqlparse doesn't support custom separator. now I change the implementation and don't need this feature, thanks.
