### ISSUE TITLE
Capitalization formatting is correct when keyword is used without parentheses, incorrect only when used with parentheses.

### ISSUE THREAD

**Issue by pradipsparkale** [andialbrecht/sqlparse#665]
Capitalization formatting is correct when keyword is used without parentheses, incorrect only when used with parentheses.

Ex: SELECT COUNT column_x FROM table_a; is formatted correctly, but SELECT count(column_x) FROM table_a; is formatted incorrectly.

**Comment by andialbrecht** [comment]
With parentheses it's a function and not a keyword anymore.
