### ISSUE TITLE
Error when copying a statement

### ISSUE THREAD

**Issue by BStevanoski** [andialbrecht/sqlparse#672]
The following minimal code yields an error.

Code:
```
import sqlparse
import copy

query = 'SELECT * FROM adults WHERE age < 20'
parsed = sqlparse.parse(query)[0]
copied_parsed = copy.deepcopy(parsed)
```

Error:
`TypeError: '_TokenType' object is not callable`

I am using Conda environment, with Python 3.9 and the following version of the library:
`sqlparse                  0.4.2              pyhd8ed1ab_0    conda-forge`

Googling the error did not help. 

Looking forward to your response!

**Comment by BStevanoski** [comment]
@andialbrecht Please let me know if the repo is no longer maintained. :)

**Comment by andialbrecht** [comment]
> @andialbrecht Please let me know if the repo is no longer maintained. :)

it is... but sometimes it takes some time ;)

Thanks for reporting this issue!
