### ISSUE TITLE
recognize `->` as a single operator.

### ISSUE THREAD

**Issue by mtagle** [andialbrecht/sqlparse#682]
I'm aware of at least 2 sql dialects that have `->` ("arrow") operators. presto/athena use them as part of lambda expressions (https://prestodb.io/docs/current/functions/lambda.html) and postgres uses them to get things out of a json blob: https://www.postgresql.org/docs/9.4/functions-json.html

Right now, however, sqlparse does not seem to recognize `->` as an operator so if you format sql with a `->` in it with `use_space_around_operators=True`, you will end up breaking the arrow and making your sql invalid.

ie:

```
import sqlparse

sql = "select params->'name' from events"
formatted_sql = sqlparse.format(sql, use_space_around_operators=True)
print(formatted_sql)
```

will print:
```
select params - > 'name' from events
```

(note the `- >`)
Obviously a workaround is to not use `use_space_around_operators`, but it would be nice if sqlparse were aware of this as an operator.

**Comment by mrmasterplan** [comment]
Opeartors are parsed here currently. https://github.com/andialbrecht/sqlparse/blob/master/sqlparse/keywords.py#L105
can you propose a regex that would parse your operator?

**Comment by Julien00859** [comment]
We too at Odoo have the problem, we would like to use sqlparse to pretty-print SQL queries generated by our ORM but at the moment the situation is sub-optimal:

```sql
SELECT "ir_module_module"."id",
       "ir_module_module"."name",
       "ir_module_module"."category_id",
       "ir_module_module"."shortdesc"->>'en_US',
                                        "ir_module_module"."summary"->>'en_US',
                                                                       "ir_module_module"."description"->>'en_US',
                                                                                                          "ir_module_module"."author",
                                                                                                          "ir_module_module"."maintainer",
                                                                                                          "ir_module_module"."contributors",
                                                                                                          "ir_module_module"."website"
FROM "ir_module_module"
WHERE ("ir_module_module"."id" IN (...))  -- ids striped for github
```

We use JSON objects to store text indexed by lang (for i18n purpose), so we have pretty much those arrows in all our queries.
