### ISSUE TITLE
Thoughts on translator / Custom formatter support

### ISSUE THREAD

**Issue by randxie** [andialbrecht/sqlparse#702]
Great work on creating the sqlparse package!! I am wondering if you have thought about allowing translating from one SQL dialect to another, or allow custom formatter to output SQL in a different way?

Providing more contexts on my use case, in my company, we used pyparsing to implement a small SQL parser, and we have custom formatter to translate that SQL into Flink and Spark SQL. But we are tired of maintaining our own SQL parser and have started to research other solutions.

Do you foresee generating customized-format output aligns with sqlparse's roadmap?

**Comment by tobymao** [comment]
[sqlglot](https://github.com/tobymao/sqlglot) is a python parser / transpiler that was built for this use case

**Comment by randxie** [comment]
Thanks @tobymao !! Will take a look at sqlglot
