### ISSUE TITLE
Lexer.get_default_instance() not working

### ISSUE THREAD

**Issue by shadowshot-x** [andialbrecht/sqlparse#705]
Lexer.get_default_instance() is not working because the current release [0.4.3](https://github.com/andialbrecht/sqlparse/releases/tag/0.4.3) does not have the updated code for lexer in source code. Can you please fix it?

**Comment by andialbrecht** [comment]
I'm not sure what the actual problem is and I'm closing this issue now.

Feel free to reopen it with steps on reproducing the problem, if your issue still exists.
