### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [andialbrecht/sqlparse#732]
Is it possible next time on release new version make the github release to have entry on https://github.com/andialbrecht/sqlparse/releases entry? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by andialbrecht** [comment]
AFAIK there's no way to subscribe on PyPI to get notified so watching releases here sounds reasonable.

I'll add an release entry here for the next release, but just as a record. No automagic changelog, no file uploads.
