### ISSUE TITLE
Condensed CASE WHEN formatting

### ISSUE THREAD

**Issue by mhmtsoydam** [andialbrecht/sqlparse#783]
Currently the parser gives the output in a very long format for CASE WHENs, it can take a lot of space when it is a simple filtering.

```
                      CASE
                          WHEN condition_1 THEN result_1
                          ELSE NULL
                      END
```

For simple CASE WHENs where there are only 1 WHEN statement and 1 ELSE statement the parser could give the output as:

```
                      CASE WHEN condition_1 THEN result_1 ELSE result_2 END
```

Everyone's use case is different but such simple filtering as above, multiple lines can really make it difficult to read.

**Comment by andialbrecht** [comment]
@mhmtsoydam nice idea, thanks! Will be available in the next version!
